apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: instances.landscaper-service.gardener.cloud
spec:
  group: landscaper-service.gardener.cloud
  names:
    kind: Instance
    plural: instances
    shortNames:
    - instc
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.serviceTargetConfigRef.name
      name: ServiceTargetConfig
      type: string
    - jsonPath: .status.installationRef.name
      name: Installation
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: The Instance is created for each LandscaperDeployment. The landscaper
          service controller selects a suitable/available ServiceTargetConfig and
          creates an Installation.
        properties:
          spec:
            description: Spec contains the specification for the Instance.
            properties:
              id:
                description: ID is the id of this instance
                type: string
              landscaperConfiguration:
                description: LandscaperConfiguration contains the configuration for
                  the landscaper service deployment
                properties:
                  deployers:
                    description: Deployers is the list of deployers that are getting
                      installed alongside with this Instance.
                    items:
                      type: string
                    type: array
                required:
                - deployers
                type: object
              oidcConfig:
                description: OIDCConfig describes the OIDC config of the customer
                  resource cluster (shoot cluster)
                properties:
                  clientID:
                    type: string
                  groupsClaim:
                    type: string
                  issuerURL:
                    type: string
                  usernameClaim:
                    type: string
                type: object
              serviceTargetConfigRef:
                description: ServiceTargetConfigRef specifies the target cluster for
                  which the installation is created.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              tenantId:
                description: TenantId is the unique identifier of the owning tenant.
                type: string
            required:
            - tenantId
            - id
            - landscaperConfiguration
            - serviceTargetConfigRef
            type: object
          status:
            description: Status contains the status for the Instance.
            properties:
              adminKubeconfig:
                description: AdminKubeconfig contains the admin kubeconfig which can
                  be used for accessing the landscaper cluster.
                type: string
              clusterEndpoint:
                description: ClusterEndpointRef contains the URL at which the landscaper
                  cluster is accessible.
                type: string
              contextRef:
                description: ContextRef references the landscaper context for this
                  Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              installationRef:
                description: InstallationRef references the Installation for this
                  Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              landscaperServiceComponent:
                description: LandscaperServiceComponent define the landscaper server
                  component that is used for this instance.
                properties:
                  name:
                    description: Name defines the component name of the landscaper
                      service component.
                    type: string
                  version:
                    description: Version defines the version of the landscaper service
                      component.
                    type: string
                required:
                - name
                - version
                type: object
              lastError:
                description: LastError describes the last error that occurred.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: Last time the condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human-readable message indicating details about
                      the transition.
                    type: string
                  operation:
                    description: Operation describes the operator where the error
                      occurred.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                required:
                - operation
                - lastTransitionTime
                - lastUpdateTime
                - reason
                - message
                type: object
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this Instance. It corresponds to the Instance generation, which
                  is updated on mutation by the landscaper service controller.
                format: int64
                type: integer
              shootName:
                description: ShootName is the name of the corresponding shoot cluster.
                type: string
              shootNamespace:
                description: ShootNamespace is the namespace in which the shoot resource
                  is being created.
                type: string
              targetRef:
                description: TargetRef references the Target for this Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              userKubeconfig:
                description: UserKubeconfig contains the user kubeconfig which can
                  be used for accessing the landscaper cluster.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
