apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: instances.landscaper-service.gardener.cloud
spec:
  group: landscaper-service.gardener.cloud
  names:
    kind: Instance
    plural: instances
    shortNames:
    - instc
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.serviceTargetConfigRef.name
      name: ServiceTargetConfig
      type: string
    - jsonPath: .status.installationRef.name
      name: Installation
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: The Instance is created for each LandscaperDeployment. The landscaper
          service controller selects a suitable/available ServiceTargetConfig and
          creates an Installation.
        properties:
          spec:
            description: Spec contains the specification for the Instance.
            properties:
              automaticReconcile:
                description: AutomaticReconcile specifies the configuration on when
                  this instance is being automatically reconciled.
                properties:
                  interval:
                    description: Interval specifies the interval after which the instance
                      is being automatically reconciled.
                    type: string
                required:
                - interval
                type: object
              dataPlane:
                properties:
                  kubeconfig:
                    type: string
                  secretRef:
                    description: SecretReference is a reference to data in a secret.
                    properties:
                      key:
                        description: Key is the name of the key in the secret that
                          holds the data.
                        type: string
                      name:
                        description: Name is the name of the kubernetes object.
                        type: string
                      namespace:
                        description: Namespace is the namespace of kubernetes object.
                        type: string
                    required:
                    - name
                    type: object
                required:
                - secretRef
                - kubeconfig
                type: object
              id:
                description: ID is the id of this instance
                type: string
              landscaperConfiguration:
                description: LandscaperConfiguration contains the configuration for
                  the landscaper service deployment
                properties:
                  deployers:
                    description: Deployers is the list of deployers that are getting
                      installed alongside with this Instance.
                    items:
                      type: string
                    type: array
                  deployersConfig:
                    additionalProperties:
                      description: DeployerConfig configures a deployer.
                      properties:
                        deployer:
                          properties:
                            controller:
                              description: Controller specifies the config for a landscaper
                                controller.
                              properties:
                                workers:
                                  format: int32
                                  type: integer
                              type: object
                            k8sClientSettings:
                              description: K8SClientSettings specifies the settings
                                for the k8s clients which landscaper uses to access
                                host and resource cluster.
                              properties:
                                hostClient:
                                  description: K8SClientLimits specifies the settings
                                    for a k8s client.
                                  properties:
                                    burst:
                                      format: int32
                                      type: integer
                                    qps:
                                      format: int32
                                      type: integer
                                  type: object
                                resourceClient:
                                  description: K8SClientLimits specifies the settings
                                    for a k8s client.
                                  properties:
                                    burst:
                                      format: int32
                                      type: integer
                                    qps:
                                      format: int32
                                      type: integer
                                  type: object
                              type: object
                          type: object
                        hpa:
                          description: HPA configures the horizontal pod autoscaling
                            of pods.
                          properties:
                            averageCpuUtilization:
                              format: int32
                              type: integer
                            averageMemoryUtilization:
                              format: int32
                              type: integer
                            maxReplicas:
                              format: int32
                              type: integer
                          type: object
                        resources:
                          description: Resources configures the resources of pods
                            (requested cpu and memory)
                          properties:
                            requests:
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                              type: object
                          type: object
                      type: object
                    description: DeployersConfig specifies the configuration for the
                      landscaper standard deployers.
                    type: object
                  hpaMain:
                    description: HPAMain configures the horizontal pod autoscaling
                      of the "main" landscaper pods, i.e. the pods of installation
                      and execution controller.
                    properties:
                      averageCpuUtilization:
                        format: int32
                        type: integer
                      averageMemoryUtilization:
                        format: int32
                        type: integer
                      maxReplicas:
                        format: int32
                        type: integer
                    type: object
                  landscaper:
                    properties:
                      controllers:
                        description: Controllers specifies the config for the "main"
                          landscaper controllers, i.e. the installation and execution
                          controller.
                        properties:
                          executions:
                            description: Controller specifies the config for a landscaper
                              controller.
                            properties:
                              workers:
                                format: int32
                                type: integer
                            type: object
                          installations:
                            description: Controller specifies the config for a landscaper
                              controller.
                            properties:
                              workers:
                                format: int32
                                type: integer
                            type: object
                        type: object
                      deployItemTimeouts:
                        description: DeployItemTimeouts configures the timeout controller.
                        properties:
                          pickup:
                            type: string
                          progressingDefault:
                            type: string
                        type: object
                      k8sClientSettings:
                        description: K8SClientSettings specifies the settings for
                          the k8s clients which landscaper uses to access host and
                          resource cluster.
                        properties:
                          hostClient:
                            description: K8SClientLimits specifies the settings for
                              a k8s client.
                            properties:
                              burst:
                                format: int32
                                type: integer
                              qps:
                                format: int32
                                type: integer
                            type: object
                          resourceClient:
                            description: K8SClientLimits specifies the settings for
                              a k8s client.
                            properties:
                              burst:
                                format: int32
                                type: integer
                              qps:
                                format: int32
                                type: integer
                            type: object
                        type: object
                    type: object
                  resources:
                    description: Resources configures the resources of the "central"
                      landscaper pod, i.e. the pod responsible for crds creation,
                      deployer management, context controller.
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  resourcesMain:
                    description: ResourcesMain configures the resources of the "main"
                      landscaper pods, i.e. the pods of installation and execution
                      controller.
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                required:
                - deployers
                type: object
              serviceTargetConfigRef:
                description: ServiceTargetConfigRef specifies the target cluster for
                  which the installation is created.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              tenantId:
                description: TenantId is the unique identifier of the owning tenant.
                type: string
            required:
            - tenantId
            - id
            - landscaperConfiguration
            - serviceTargetConfigRef
            - dataPlane
            type: object
          status:
            description: Status contains the status for the Instance.
            properties:
              adminKubeconfig:
                description: AdminKubeconfig contains the admin kubeconfig which can
                  be used for accessing the landscaper cluster.
                type: string
              clusterEndpoint:
                description: ClusterEndpointRef contains the URL at which the landscaper
                  cluster is accessible.
                type: string
              contextRef:
                description: ContextRef references the landscaper context for this
                  Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              gardenerServiceAccountRef:
                description: GardenerServiceAccountRef references the Target for the
                  Gardener service account.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              installationRef:
                description: InstallationRef references the Installation for this
                  Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              landscaperServiceComponent:
                description: LandscaperServiceComponent define the landscaper server
                  component that is used for this instance.
                properties:
                  name:
                    description: Name defines the component name of the landscaper
                      service component.
                    type: string
                  version:
                    description: Version defines the version of the landscaper service
                      component.
                    type: string
                required:
                - name
                - version
                type: object
              lastError:
                description: LastError describes the last error that occurred.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: Last time the condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human-readable message indicating details about
                      the transition.
                    type: string
                  operation:
                    description: Operation describes the operator where the error
                      occurred.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                required:
                - operation
                - lastTransitionTime
                - lastUpdateTime
                - reason
                - message
                type: object
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this Instance. It corresponds to the Instance generation, which
                  is updated on mutation by the landscaper service controller.
                format: int64
                type: integer
              shootName:
                description: ShootName is the name of the corresponding shoot cluster.
                type: string
              shootNamespace:
                description: ShootNamespace is the namespace in which the shoot resource
                  is being created.
                type: string
              targetRef:
                description: TargetRef references the Target for this Instance.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              userKubeconfig:
                description: UserKubeconfig contains the user kubeconfig which can
                  be used for accessing the landscaper cluster.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
