apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: lossubjectlists.landscaper-service.gardener.cloud
spec:
  group: landscaper-service.gardener.cloud
  names:
    kind: LosSubjectList
    plural: lossubjectlists
    shortNames:
    - lossulist
    singular: lossubjectlist
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Spec contains the specification for the SubjectList.
            properties:
              admins:
                description: Admins contains references to the object or user identities
                  the admin role binding applies to.
                items:
                  description: Subject is a User, Group or ServiceAccount(with namespace).
                    Similar to rbac.Subject struct but does not depend on it to prevent
                    future k8s version from breaking this logic.
                  properties:
                    kind:
                      description: Kind of object being referenced. Values defined
                        by this API group are "User", "Group", and "ServiceAccount".
                        If the Authorizer does not recognized the kind value, the
                        Authorizer should report an error.
                      type: string
                    name:
                      description: Name of the object being referenced.
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
              members:
                description: Members contains references to the object or user identities
                  the member role binding applies to.
                items:
                  description: Subject is a User, Group or ServiceAccount(with namespace).
                    Similar to rbac.Subject struct but does not depend on it to prevent
                    future k8s version from breaking this logic.
                  properties:
                    kind:
                      description: Kind of object being referenced. Values defined
                        by this API group are "User", "Group", and "ServiceAccount".
                        If the Authorizer does not recognized the kind value, the
                        Authorizer should report an error.
                      type: string
                    name:
                      description: Name of the object being referenced.
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
              viewer:
                description: Viewer contains references to the object or user identities
                  the viewer role binding applies to.
                items:
                  description: Subject is a User, Group or ServiceAccount(with namespace).
                    Similar to rbac.Subject struct but does not depend on it to prevent
                    future k8s version from breaking this logic.
                  properties:
                    kind:
                      description: Kind of object being referenced. Values defined
                        by this API group are "User", "Group", and "ServiceAccount".
                        If the Authorizer does not recognized the kind value, the
                        Authorizer should report an error.
                      type: string
                    name:
                      description: Name of the object being referenced.
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
            required:
            - admins
            - members
            - viewer
            type: object
          status:
            description: Status contains the status for the SubjectList.
            properties:
              observedGeneration:
                format: int64
                type: integer
              phase:
                type: string
              syncedGeneration:
                format: int64
                type: integer
            required:
            - phase
            - syncedGeneration
            - observedGeneration
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
