# SPDX-FileCopyrightText: 2023 "SAP SE or an SAP affiliate company and Gardener contributors"
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.landscaperservice.auditLogConfiguration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "landscaper-service.fullname" . }}-audit-policy
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
data:
  policy: |-
{{ toYaml .Values.landscaperservice.auditLogConfiguration.auditPolicy | indent 4 }}
{{- end }}
