{{/* SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"

  SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.controller.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "landscaper-service.controller.serviceAccountName" . }}
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "landscaper-service.controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "landscaper-service.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.serviceAccount.webhooksServer.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "landscaper-service.webhooksServer.serviceAccountName" . }}
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "landscaper-service.webhooksServer.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "landscaper-service.webhooksServer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
