{{/* SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper-service.fullname" . }}-config
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "landscaper-service-config" . | b64enc }}
