{{/* SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"

  SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.controller.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "landscaper-service.controller.serviceAccountName" . }}
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.webhooksServer.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "landscaper-service.webhooksServer.serviceAccountName" . }}
  labels:
    {{- include "landscaper-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.webhooksServer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
