apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: gardenerServiceAccount
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: name
    required: true
    type: data
    schema:
      type: string

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: secretBindingName
    required: true
    type: data
    schema:
      type: string

  - name: labels
    required: false
    type: data
    schema:
      type: object

  - name: shootConfig
    required: true
    type: data
    schema:
      $ref: "cd://resources/shoot-config-definition"

  - name: auditPolicy
    required: false
    type: data
    schema:
      type: object

  - name: auditLogService
    required: false
    type: data
    schema:
      type: object
      properties:
        tenantId:
          type: string
        url:
          type: string
        user:
          type: string
        password:
          type: string
      required:
        - tenantId
        - url
        - user
        - password

  - name: rotationConfig
    type: data
    schema:
      description: |
        The configuration for the rotation of credentials.
      $ref: "cd://resources/rotation-config-definition"

exports:
  - name: shootClusterKubeconfig
    type: data
    schema:
      type: string

  - name: shootClusterEndpoint
    type: data
    schema:
      type: string

  - name: shootCluster
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate
