---
name: github_com_gardener_landscaper_service
type: git
version: ${VERSION}
labels:
  - name: cloud.gardener/cicd/source
    value:
      repository-classification: main
access:
  type: github
  commit: ${COMMIT_SHA}
  ref: refs/tags/${VERSION}
  repoUrl: github.com/gardener/landscaper-service
---