apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: fluentbitClusters
    required: true
    type: targetList
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: serviceManager
    required: true
    type: data
    schema:
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
        smURL:
          type: string
        tokenURL:
          type: string
      required:
        - clientId
        - clientSecret
        - smURL
        - tokenURL

  - name: cloudLoggingService
    required: true
    type: data
    schema:
      type: object
      properties:
        name:
          type: string
        plan:
          type: string
        instanceParameters:
          type: object
          properties: {}
        bindingParameters:
          properties: {}
      required:
        - name
        - plan

  - name: fluentBit
    required: true
    type: data
    schema:
      type: object
      properties:
        namespace:
          type: string
        kubernetesInputPath:
          type: string
        kubernetesExcludePath:
          type: string
      required:
        - namespace
        - kubernetesInputPath
        - kubernetesExcludePath

exports:
  - name: dashboard
    type: data
    schema:
      type: object
      properties:
        endpoint:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - endpoint
        - username
        - password

  - name: dashboardEndpoint
    type: data
    schema:
      type: string

  - name: dashboardUsername
    type: data
    schema:
      type: string

  - name: dashboardPassword
    type: data
    schema:
      type: string

exportExecutions:
  - name: export
    type: GoTemplate
    template: |
      exports:
        dashboard:
          endpoint: {{ .values.dataobjects.kibanaEndpoint }}
          username: {{ .values.dataobjects.kibanaUsername }}
          password: {{ .values.dataobjects.kibanaPassword }}
        dashboardEndpoint: {{ .values.dataobjects.kibanaEndpoint }}
        dashboardUsername: {{ .values.dataobjects.kibanaUsername }}
        dashboardPassword: {{ .values.dataobjects.kibanaPassword }}

subinstallations:
  - file: /cert-manager-subinst.yaml
  - file: /sap-btp-service-operator-subinst.yaml
  - file: /service-provisioning-subinst.yaml
  - file: /fluentbit-subinst.yaml
