apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: cert-manager

blueprint:
  ref: cd://resources/cert-manager-blueprint

imports:
  targets:
    - name: targetCluster
      target: targetCluster
  data:
    - name: namespace
      dataRef: namespace

exports:
  data:
    - name: certManagerReady
      dataRef: certManagerReady
