apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: fluentbit

blueprint:
  ref: cd://resources/fluentbit-blueprint

imports:
  targets:
    - name: fluentbitClusters
      targetListRef: fluentbitClusters

  data:
    - name: fluentBit
      dataRef: fluentBit
    - name: fluentdEndpoint
      dataRef: fluentdEndpoint
    - name: fluentdUsername
      dataRef: fluentdUsername
    - name: fluentdPassword
      dataRef: fluentdPassword

importDataMappings:
  namespace: (( fluentBit.namespace ))
  kubernetesInputPath: (( fluentBit.kubernetesInputPath ))
  kubernetesExcludePath: (( fluentBit.kubernetesExcludePath ))
