apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: sap-btp-service-operator

blueprint:
  ref: cd://resources/sap-btp-service-operator-blueprint

imports:
  targets:
    - name: targetCluster
      target: targetCluster
  data:
    - name: namespace
      dataRef: namespace
    - name: certManagerReady
      dataRef: certManagerReady
    - name: serviceManager
      dataRef: serviceManager

importDataMappings:
  clientId: (( serviceManager.clientId ))
  clientSecret: (( serviceManager.clientSecret ))
  smURL: (( serviceManager.smURL ))
  tokenURL: (( serviceManager.tokenURL ))

exports:
  data:
    - name: btpOperatorReady
      dataRef: btpOperatorReady
