apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: service-provisioning

blueprint:
  ref: cd://resources/service-provisioning-blueprint

imports:
  targets:
    - name: targetCluster
      target: targetCluster
  data:
    - name: namespace
      dataRef: namespace
    - name: btpOperatorReady
      dataRef: btpOperatorReady
    - name: cloudLoggingService
      dataRef: cloudLoggingService

importDataMappings:
  name: (( cloudLoggingService.name ))
  plan: (( cloudLoggingService.plan ))
  serviceInstanceParameters: (( cloudLoggingService.instanceParameters || {} ))
  serviceBindingParameters: (( cloudLoggingService.bindingParameters || {} ))

exports:
  data:
    - name: fluentdEndpoint
      dataRef: fluentdEndpoint
    - name: fluentdUsername
      dataRef: fluentdUsername
    - name: fluentdPassword
      dataRef: fluentdPassword
    - name: kibanaEndpoint
      dataRef: kibanaEndpoint
    - name: kibanaUsername
      dataRef: kibanaUsername
    - name: kibanaPassword
      dataRef: kibanaPassword
