apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: targetClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: dataPlaneClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: landscaperControllerKubeconfigYaml
    required: true
    type: data
    schema:
      type: string

  - name: landscaperWebhooksKubeconfigYaml
    required: true
    type: data
    schema:
      type: string

  - name: registryConfig
    type: data
    schema:
      $ref: "cd://resources/registry-config-definition"

  - name: landscaperConfig
    type: data
    schema:
      $ref: "cd://resources/landscaper-config-definition"

  - name: webhooksHostName
    required: true
    type: data
    schema:
      type: string

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
