//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	config "github.com/gardener/landscaper-service/pkg/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuditLogConfiguration)(nil), (*config.AuditLogConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuditLogConfiguration_To_config_AuditLogConfiguration(a.(*AuditLogConfiguration), b.(*config.AuditLogConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AuditLogConfiguration)(nil), (*AuditLogConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AuditLogConfiguration_To_v1alpha1_AuditLogConfiguration(a.(*config.AuditLogConfiguration), b.(*AuditLogConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityMonitoringConfiguration)(nil), (*config.AvailabilityMonitoringConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration(a.(*AvailabilityMonitoringConfiguration), b.(*config.AvailabilityMonitoringConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AvailabilityMonitoringConfiguration)(nil), (*AvailabilityMonitoringConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration(a.(*config.AvailabilityMonitoringConfiguration), b.(*AvailabilityMonitoringConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityServiceConfiguration)(nil), (*config.AvailabilityServiceConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AvailabilityServiceConfiguration_To_config_AvailabilityServiceConfiguration(a.(*AvailabilityServiceConfiguration), b.(*config.AvailabilityServiceConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AvailabilityServiceConfiguration)(nil), (*AvailabilityServiceConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AvailabilityServiceConfiguration_To_v1alpha1_AvailabilityServiceConfiguration(a.(*config.AvailabilityServiceConfiguration), b.(*AvailabilityServiceConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CrdManagementConfiguration)(nil), (*config.CrdManagementConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration(a.(*CrdManagementConfiguration), b.(*config.CrdManagementConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CrdManagementConfiguration)(nil), (*CrdManagementConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration(a.(*config.CrdManagementConfiguration), b.(*CrdManagementConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GardenerConfiguration)(nil), (*config.GardenerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration(a.(*GardenerConfiguration), b.(*config.GardenerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GardenerConfiguration)(nil), (*GardenerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration(a.(*config.GardenerConfiguration), b.(*GardenerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperServiceComponentConfiguration)(nil), (*config.LandscaperServiceComponentConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration(a.(*LandscaperServiceComponentConfiguration), b.(*config.LandscaperServiceComponentConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LandscaperServiceComponentConfiguration)(nil), (*LandscaperServiceComponentConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration(a.(*config.LandscaperServiceComponentConfiguration), b.(*LandscaperServiceComponentConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperServiceConfiguration)(nil), (*config.LandscaperServiceConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscaperServiceConfiguration_To_config_LandscaperServiceConfiguration(a.(*LandscaperServiceConfiguration), b.(*config.LandscaperServiceConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LandscaperServiceConfiguration)(nil), (*LandscaperServiceConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LandscaperServiceConfiguration_To_v1alpha1_LandscaperServiceConfiguration(a.(*config.LandscaperServiceConfiguration), b.(*LandscaperServiceConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricsConfiguration)(nil), (*config.MetricsConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricsConfiguration_To_config_MetricsConfiguration(a.(*MetricsConfiguration), b.(*config.MetricsConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MetricsConfiguration)(nil), (*MetricsConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MetricsConfiguration_To_v1alpha1_MetricsConfiguration(a.(*config.MetricsConfiguration), b.(*MetricsConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootAutoUpdateConfig)(nil), (*config.ShootAutoUpdateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig(a.(*ShootAutoUpdateConfig), b.(*config.ShootAutoUpdateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootAutoUpdateConfig)(nil), (*ShootAutoUpdateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig(a.(*config.ShootAutoUpdateConfig), b.(*ShootAutoUpdateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootConfiguration)(nil), (*config.ShootConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration(a.(*ShootConfiguration), b.(*config.ShootConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootConfiguration)(nil), (*ShootConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration(a.(*config.ShootConfiguration), b.(*ShootConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootKubernetesConfig)(nil), (*config.ShootKubernetesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig(a.(*ShootKubernetesConfig), b.(*config.ShootKubernetesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootKubernetesConfig)(nil), (*ShootKubernetesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig(a.(*config.ShootKubernetesConfig), b.(*ShootKubernetesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootMachineConfiguration)(nil), (*config.ShootMachineConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration(a.(*ShootMachineConfiguration), b.(*config.ShootMachineConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootMachineConfiguration)(nil), (*ShootMachineConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration(a.(*config.ShootMachineConfiguration), b.(*ShootMachineConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootMachineImage)(nil), (*config.ShootMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage(a.(*ShootMachineImage), b.(*config.ShootMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootMachineImage)(nil), (*ShootMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage(a.(*config.ShootMachineImage), b.(*ShootMachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootMaintenanceConfig)(nil), (*config.ShootMaintenanceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig(a.(*ShootMaintenanceConfig), b.(*config.ShootMaintenanceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootMaintenanceConfig)(nil), (*ShootMaintenanceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig(a.(*config.ShootMaintenanceConfig), b.(*ShootMaintenanceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootMaintenanceTimeWindow)(nil), (*config.ShootMaintenanceTimeWindow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow(a.(*ShootMaintenanceTimeWindow), b.(*config.ShootMaintenanceTimeWindow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootMaintenanceTimeWindow)(nil), (*ShootMaintenanceTimeWindow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow(a.(*config.ShootMaintenanceTimeWindow), b.(*ShootMaintenanceTimeWindow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootProviderConfiguration)(nil), (*config.ShootProviderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration(a.(*ShootProviderConfiguration), b.(*config.ShootProviderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootProviderConfiguration)(nil), (*ShootProviderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration(a.(*config.ShootProviderConfiguration), b.(*ShootProviderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootWorkerVolumeConfiguration)(nil), (*config.ShootWorkerVolumeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration(a.(*ShootWorkerVolumeConfiguration), b.(*config.ShootWorkerVolumeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootWorkerVolumeConfiguration)(nil), (*ShootWorkerVolumeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration(a.(*config.ShootWorkerVolumeConfiguration), b.(*ShootWorkerVolumeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootWorkersConfiguration)(nil), (*config.ShootWorkersConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration(a.(*ShootWorkersConfiguration), b.(*config.ShootWorkersConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootWorkersConfiguration)(nil), (*ShootWorkersConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration(a.(*config.ShootWorkersConfiguration), b.(*ShootWorkersConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuditLogConfiguration_To_config_AuditLogConfiguration(in *AuditLogConfiguration, out *config.AuditLogConfiguration, s conversion.Scope) error {
	out.SubAccountId = in.SubAccountId
	out.AuditPolicy = in.AuditPolicy
	return nil
}

// Convert_v1alpha1_AuditLogConfiguration_To_config_AuditLogConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AuditLogConfiguration_To_config_AuditLogConfiguration(in *AuditLogConfiguration, out *config.AuditLogConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuditLogConfiguration_To_config_AuditLogConfiguration(in, out, s)
}

func autoConvert_config_AuditLogConfiguration_To_v1alpha1_AuditLogConfiguration(in *config.AuditLogConfiguration, out *AuditLogConfiguration, s conversion.Scope) error {
	out.SubAccountId = in.SubAccountId
	out.AuditPolicy = in.AuditPolicy
	return nil
}

// Convert_config_AuditLogConfiguration_To_v1alpha1_AuditLogConfiguration is an autogenerated conversion function.
func Convert_config_AuditLogConfiguration_To_v1alpha1_AuditLogConfiguration(in *config.AuditLogConfiguration, out *AuditLogConfiguration, s conversion.Scope) error {
	return autoConvert_config_AuditLogConfiguration_To_v1alpha1_AuditLogConfiguration(in, out, s)
}

func autoConvert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration(in *AvailabilityMonitoringConfiguration, out *config.AvailabilityMonitoringConfiguration, s conversion.Scope) error {
	out.AvailabilityCollectionName = in.AvailabilityCollectionName
	out.AvailabilityCollectionNamespace = in.AvailabilityCollectionNamespace
	out.AvailabilityServiceConfiguration = (*config.AvailabilityServiceConfiguration)(unsafe.Pointer(in.AvailabilityServiceConfiguration))
	out.SelfLandscaperNamespace = in.SelfLandscaperNamespace
	out.PeriodicCheckInterval = in.PeriodicCheckInterval
	out.LSHealthCheckTimeout = in.LSHealthCheckTimeout
	return nil
}

// Convert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration(in *AvailabilityMonitoringConfiguration, out *config.AvailabilityMonitoringConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration(in, out, s)
}

func autoConvert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration(in *config.AvailabilityMonitoringConfiguration, out *AvailabilityMonitoringConfiguration, s conversion.Scope) error {
	out.AvailabilityCollectionName = in.AvailabilityCollectionName
	out.AvailabilityCollectionNamespace = in.AvailabilityCollectionNamespace
	out.AvailabilityServiceConfiguration = (*AvailabilityServiceConfiguration)(unsafe.Pointer(in.AvailabilityServiceConfiguration))
	out.SelfLandscaperNamespace = in.SelfLandscaperNamespace
	out.PeriodicCheckInterval = in.PeriodicCheckInterval
	out.LSHealthCheckTimeout = in.LSHealthCheckTimeout
	return nil
}

// Convert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration is an autogenerated conversion function.
func Convert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration(in *config.AvailabilityMonitoringConfiguration, out *AvailabilityMonitoringConfiguration, s conversion.Scope) error {
	return autoConvert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration(in, out, s)
}

func autoConvert_v1alpha1_AvailabilityServiceConfiguration_To_config_AvailabilityServiceConfiguration(in *AvailabilityServiceConfiguration, out *config.AvailabilityServiceConfiguration, s conversion.Scope) error {
	out.Url = in.Url
	out.ApiKey = in.ApiKey
	out.Timeout = in.Timeout
	return nil
}

// Convert_v1alpha1_AvailabilityServiceConfiguration_To_config_AvailabilityServiceConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AvailabilityServiceConfiguration_To_config_AvailabilityServiceConfiguration(in *AvailabilityServiceConfiguration, out *config.AvailabilityServiceConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AvailabilityServiceConfiguration_To_config_AvailabilityServiceConfiguration(in, out, s)
}

func autoConvert_config_AvailabilityServiceConfiguration_To_v1alpha1_AvailabilityServiceConfiguration(in *config.AvailabilityServiceConfiguration, out *AvailabilityServiceConfiguration, s conversion.Scope) error {
	out.Url = in.Url
	out.ApiKey = in.ApiKey
	out.Timeout = in.Timeout
	return nil
}

// Convert_config_AvailabilityServiceConfiguration_To_v1alpha1_AvailabilityServiceConfiguration is an autogenerated conversion function.
func Convert_config_AvailabilityServiceConfiguration_To_v1alpha1_AvailabilityServiceConfiguration(in *config.AvailabilityServiceConfiguration, out *AvailabilityServiceConfiguration, s conversion.Scope) error {
	return autoConvert_config_AvailabilityServiceConfiguration_To_v1alpha1_AvailabilityServiceConfiguration(in, out, s)
}

func autoConvert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration(in *CrdManagementConfiguration, out *config.CrdManagementConfiguration, s conversion.Scope) error {
	out.DeployCustomResourceDefinitions = (*bool)(unsafe.Pointer(in.DeployCustomResourceDefinitions))
	out.ForceUpdate = (*bool)(unsafe.Pointer(in.ForceUpdate))
	return nil
}

// Convert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration(in *CrdManagementConfiguration, out *config.CrdManagementConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration(in, out, s)
}

func autoConvert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration(in *config.CrdManagementConfiguration, out *CrdManagementConfiguration, s conversion.Scope) error {
	out.DeployCustomResourceDefinitions = (*bool)(unsafe.Pointer(in.DeployCustomResourceDefinitions))
	out.ForceUpdate = (*bool)(unsafe.Pointer(in.ForceUpdate))
	return nil
}

// Convert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration is an autogenerated conversion function.
func Convert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration(in *config.CrdManagementConfiguration, out *CrdManagementConfiguration, s conversion.Scope) error {
	return autoConvert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration(in, out, s)
}

func autoConvert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration(in *GardenerConfiguration, out *config.GardenerConfiguration, s conversion.Scope) error {
	out.ServiceAccountKubeconfig = in.ServiceAccountKubeconfig
	out.ProjectName = in.ProjectName
	out.ShootSecretBindingName = in.ShootSecretBindingName
	return nil
}

// Convert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration(in *GardenerConfiguration, out *config.GardenerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration(in, out, s)
}

func autoConvert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration(in *config.GardenerConfiguration, out *GardenerConfiguration, s conversion.Scope) error {
	out.ServiceAccountKubeconfig = in.ServiceAccountKubeconfig
	out.ProjectName = in.ProjectName
	out.ShootSecretBindingName = in.ShootSecretBindingName
	return nil
}

// Convert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration is an autogenerated conversion function.
func Convert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration(in *config.GardenerConfiguration, out *GardenerConfiguration, s conversion.Scope) error {
	return autoConvert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration(in *LandscaperServiceComponentConfiguration, out *config.LandscaperServiceComponentConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.RepositoryContext = in.RepositoryContext
	out.RegistryPullSecrets = *(*[]v1.SecretReference)(unsafe.Pointer(&in.RegistryPullSecrets))
	return nil
}

// Convert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration(in *LandscaperServiceComponentConfiguration, out *config.LandscaperServiceComponentConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration(in, out, s)
}

func autoConvert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration(in *config.LandscaperServiceComponentConfiguration, out *LandscaperServiceComponentConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.RepositoryContext = in.RepositoryContext
	out.RegistryPullSecrets = *(*[]v1.SecretReference)(unsafe.Pointer(&in.RegistryPullSecrets))
	return nil
}

// Convert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration is an autogenerated conversion function.
func Convert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration(in *config.LandscaperServiceComponentConfiguration, out *LandscaperServiceComponentConfiguration, s conversion.Scope) error {
	return autoConvert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LandscaperServiceConfiguration_To_config_LandscaperServiceConfiguration(in *LandscaperServiceConfiguration, out *config.LandscaperServiceConfiguration, s conversion.Scope) error {
	out.Metrics = (*config.MetricsConfiguration)(unsafe.Pointer(in.Metrics))
	if err := Convert_v1alpha1_AvailabilityMonitoringConfiguration_To_config_AvailabilityMonitoringConfiguration(&in.AvailabilityMonitoring, &out.AvailabilityMonitoring, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CrdManagementConfiguration_To_config_CrdManagementConfiguration(&in.CrdManagement, &out.CrdManagement, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LandscaperServiceComponentConfiguration_To_config_LandscaperServiceComponentConfiguration(&in.LandscaperServiceComponent, &out.LandscaperServiceComponent, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_GardenerConfiguration_To_config_GardenerConfiguration(&in.GardenerConfiguration, &out.GardenerConfiguration, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration(&in.ShootConfiguration, &out.ShootConfiguration, s); err != nil {
		return err
	}
	out.AuditLogConfig = (*config.AuditLogConfiguration)(unsafe.Pointer(in.AuditLogConfig))
	return nil
}

// Convert_v1alpha1_LandscaperServiceConfiguration_To_config_LandscaperServiceConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LandscaperServiceConfiguration_To_config_LandscaperServiceConfiguration(in *LandscaperServiceConfiguration, out *config.LandscaperServiceConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscaperServiceConfiguration_To_config_LandscaperServiceConfiguration(in, out, s)
}

func autoConvert_config_LandscaperServiceConfiguration_To_v1alpha1_LandscaperServiceConfiguration(in *config.LandscaperServiceConfiguration, out *LandscaperServiceConfiguration, s conversion.Scope) error {
	out.Metrics = (*MetricsConfiguration)(unsafe.Pointer(in.Metrics))
	if err := Convert_config_AvailabilityMonitoringConfiguration_To_v1alpha1_AvailabilityMonitoringConfiguration(&in.AvailabilityMonitoring, &out.AvailabilityMonitoring, s); err != nil {
		return err
	}
	if err := Convert_config_CrdManagementConfiguration_To_v1alpha1_CrdManagementConfiguration(&in.CrdManagement, &out.CrdManagement, s); err != nil {
		return err
	}
	if err := Convert_config_LandscaperServiceComponentConfiguration_To_v1alpha1_LandscaperServiceComponentConfiguration(&in.LandscaperServiceComponent, &out.LandscaperServiceComponent, s); err != nil {
		return err
	}
	if err := Convert_config_GardenerConfiguration_To_v1alpha1_GardenerConfiguration(&in.GardenerConfiguration, &out.GardenerConfiguration, s); err != nil {
		return err
	}
	if err := Convert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration(&in.ShootConfiguration, &out.ShootConfiguration, s); err != nil {
		return err
	}
	out.AuditLogConfig = (*AuditLogConfiguration)(unsafe.Pointer(in.AuditLogConfig))
	return nil
}

// Convert_config_LandscaperServiceConfiguration_To_v1alpha1_LandscaperServiceConfiguration is an autogenerated conversion function.
func Convert_config_LandscaperServiceConfiguration_To_v1alpha1_LandscaperServiceConfiguration(in *config.LandscaperServiceConfiguration, out *LandscaperServiceConfiguration, s conversion.Scope) error {
	return autoConvert_config_LandscaperServiceConfiguration_To_v1alpha1_LandscaperServiceConfiguration(in, out, s)
}

func autoConvert_v1alpha1_MetricsConfiguration_To_config_MetricsConfiguration(in *MetricsConfiguration, out *config.MetricsConfiguration, s conversion.Scope) error {
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_MetricsConfiguration_To_config_MetricsConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_MetricsConfiguration_To_config_MetricsConfiguration(in *MetricsConfiguration, out *config.MetricsConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricsConfiguration_To_config_MetricsConfiguration(in, out, s)
}

func autoConvert_config_MetricsConfiguration_To_v1alpha1_MetricsConfiguration(in *config.MetricsConfiguration, out *MetricsConfiguration, s conversion.Scope) error {
	out.Port = in.Port
	return nil
}

// Convert_config_MetricsConfiguration_To_v1alpha1_MetricsConfiguration is an autogenerated conversion function.
func Convert_config_MetricsConfiguration_To_v1alpha1_MetricsConfiguration(in *config.MetricsConfiguration, out *MetricsConfiguration, s conversion.Scope) error {
	return autoConvert_config_MetricsConfiguration_To_v1alpha1_MetricsConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig(in *ShootAutoUpdateConfig, out *config.ShootAutoUpdateConfig, s conversion.Scope) error {
	out.KubernetesVersion = (*bool)(unsafe.Pointer(in.KubernetesVersion))
	out.MachineImageVersion = (*bool)(unsafe.Pointer(in.MachineImageVersion))
	return nil
}

// Convert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig is an autogenerated conversion function.
func Convert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig(in *ShootAutoUpdateConfig, out *config.ShootAutoUpdateConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig(in, out, s)
}

func autoConvert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig(in *config.ShootAutoUpdateConfig, out *ShootAutoUpdateConfig, s conversion.Scope) error {
	out.KubernetesVersion = (*bool)(unsafe.Pointer(in.KubernetesVersion))
	out.MachineImageVersion = (*bool)(unsafe.Pointer(in.MachineImageVersion))
	return nil
}

// Convert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig is an autogenerated conversion function.
func Convert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig(in *config.ShootAutoUpdateConfig, out *ShootAutoUpdateConfig, s conversion.Scope) error {
	return autoConvert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig(in, out, s)
}

func autoConvert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration(in *ShootConfiguration, out *config.ShootConfiguration, s conversion.Scope) error {
	if err := Convert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration(&in.Provider, &out.Provider, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration(&in.Workers, &out.Workers, s); err != nil {
		return err
	}
	out.Region = in.Region
	if err := Convert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig(&in.Kubernetes, &out.Kubernetes, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig(&in.Maintenance, &out.Maintenance, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration(in *ShootConfiguration, out *config.ShootConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootConfiguration_To_config_ShootConfiguration(in, out, s)
}

func autoConvert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration(in *config.ShootConfiguration, out *ShootConfiguration, s conversion.Scope) error {
	if err := Convert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration(&in.Provider, &out.Provider, s); err != nil {
		return err
	}
	if err := Convert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration(&in.Workers, &out.Workers, s); err != nil {
		return err
	}
	out.Region = in.Region
	if err := Convert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig(&in.Kubernetes, &out.Kubernetes, s); err != nil {
		return err
	}
	if err := Convert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig(&in.Maintenance, &out.Maintenance, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration is an autogenerated conversion function.
func Convert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration(in *config.ShootConfiguration, out *ShootConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootConfiguration_To_v1alpha1_ShootConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig(in *ShootKubernetesConfig, out *config.ShootKubernetesConfig, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig is an autogenerated conversion function.
func Convert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig(in *ShootKubernetesConfig, out *config.ShootKubernetesConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootKubernetesConfig_To_config_ShootKubernetesConfig(in, out, s)
}

func autoConvert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig(in *config.ShootKubernetesConfig, out *ShootKubernetesConfig, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig is an autogenerated conversion function.
func Convert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig(in *config.ShootKubernetesConfig, out *ShootKubernetesConfig, s conversion.Scope) error {
	return autoConvert_config_ShootKubernetesConfig_To_v1alpha1_ShootKubernetesConfig(in, out, s)
}

func autoConvert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration(in *ShootMachineConfiguration, out *config.ShootMachineConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration(in *ShootMachineConfiguration, out *config.ShootMachineConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration(in, out, s)
}

func autoConvert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration(in *config.ShootMachineConfiguration, out *ShootMachineConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration is an autogenerated conversion function.
func Convert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration(in *config.ShootMachineConfiguration, out *ShootMachineConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage(in *ShootMachineImage, out *config.ShootMachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage is an autogenerated conversion function.
func Convert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage(in *ShootMachineImage, out *config.ShootMachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootMachineImage_To_config_ShootMachineImage(in, out, s)
}

func autoConvert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage(in *config.ShootMachineImage, out *ShootMachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage is an autogenerated conversion function.
func Convert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage(in *config.ShootMachineImage, out *ShootMachineImage, s conversion.Scope) error {
	return autoConvert_config_ShootMachineImage_To_v1alpha1_ShootMachineImage(in, out, s)
}

func autoConvert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig(in *ShootMaintenanceConfig, out *config.ShootMaintenanceConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_ShootAutoUpdateConfig_To_config_ShootAutoUpdateConfig(&in.AutoUpdate, &out.AutoUpdate, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow(&in.TimeWindow, &out.TimeWindow, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig is an autogenerated conversion function.
func Convert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig(in *ShootMaintenanceConfig, out *config.ShootMaintenanceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootMaintenanceConfig_To_config_ShootMaintenanceConfig(in, out, s)
}

func autoConvert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig(in *config.ShootMaintenanceConfig, out *ShootMaintenanceConfig, s conversion.Scope) error {
	if err := Convert_config_ShootAutoUpdateConfig_To_v1alpha1_ShootAutoUpdateConfig(&in.AutoUpdate, &out.AutoUpdate, s); err != nil {
		return err
	}
	if err := Convert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow(&in.TimeWindow, &out.TimeWindow, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig is an autogenerated conversion function.
func Convert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig(in *config.ShootMaintenanceConfig, out *ShootMaintenanceConfig, s conversion.Scope) error {
	return autoConvert_config_ShootMaintenanceConfig_To_v1alpha1_ShootMaintenanceConfig(in, out, s)
}

func autoConvert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow(in *ShootMaintenanceTimeWindow, out *config.ShootMaintenanceTimeWindow, s conversion.Scope) error {
	out.Begin = in.Begin
	out.End = in.End
	return nil
}

// Convert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow is an autogenerated conversion function.
func Convert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow(in *ShootMaintenanceTimeWindow, out *config.ShootMaintenanceTimeWindow, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootMaintenanceTimeWindow_To_config_ShootMaintenanceTimeWindow(in, out, s)
}

func autoConvert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow(in *config.ShootMaintenanceTimeWindow, out *ShootMaintenanceTimeWindow, s conversion.Scope) error {
	out.Begin = in.Begin
	out.End = in.End
	return nil
}

// Convert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow is an autogenerated conversion function.
func Convert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow(in *config.ShootMaintenanceTimeWindow, out *ShootMaintenanceTimeWindow, s conversion.Scope) error {
	return autoConvert_config_ShootMaintenanceTimeWindow_To_v1alpha1_ShootMaintenanceTimeWindow(in, out, s)
}

func autoConvert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration(in *ShootProviderConfiguration, out *config.ShootProviderConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration(in *ShootProviderConfiguration, out *config.ShootProviderConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootProviderConfiguration_To_config_ShootProviderConfiguration(in, out, s)
}

func autoConvert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration(in *config.ShootProviderConfiguration, out *ShootProviderConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	out.Zone = in.Zone
	return nil
}

// Convert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration is an autogenerated conversion function.
func Convert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration(in *config.ShootProviderConfiguration, out *ShootProviderConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootProviderConfiguration_To_v1alpha1_ShootProviderConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration(in *ShootWorkerVolumeConfiguration, out *config.ShootWorkerVolumeConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	out.Size = in.Size
	return nil
}

// Convert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration(in *ShootWorkerVolumeConfiguration, out *config.ShootWorkerVolumeConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration(in, out, s)
}

func autoConvert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration(in *config.ShootWorkerVolumeConfiguration, out *ShootWorkerVolumeConfiguration, s conversion.Scope) error {
	out.Type = in.Type
	out.Size = in.Size
	return nil
}

// Convert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration is an autogenerated conversion function.
func Convert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration(in *config.ShootWorkerVolumeConfiguration, out *ShootWorkerVolumeConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration(in *ShootWorkersConfiguration, out *config.ShootWorkersConfiguration, s conversion.Scope) error {
	if err := Convert_v1alpha1_ShootMachineConfiguration_To_config_ShootMachineConfiguration(&in.Machine, &out.Machine, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShootWorkerVolumeConfiguration_To_config_ShootWorkerVolumeConfiguration(&in.Volume, &out.Volume, s); err != nil {
		return err
	}
	out.Minimum = (*int32)(unsafe.Pointer(in.Minimum))
	out.Maximum = (*int32)(unsafe.Pointer(in.Maximum))
	out.MaxSurge = (*int32)(unsafe.Pointer(in.MaxSurge))
	out.MaxUnavailable = (*int32)(unsafe.Pointer(in.MaxUnavailable))
	return nil
}

// Convert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration(in *ShootWorkersConfiguration, out *config.ShootWorkersConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootWorkersConfiguration_To_config_ShootWorkersConfiguration(in, out, s)
}

func autoConvert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration(in *config.ShootWorkersConfiguration, out *ShootWorkersConfiguration, s conversion.Scope) error {
	if err := Convert_config_ShootMachineConfiguration_To_v1alpha1_ShootMachineConfiguration(&in.Machine, &out.Machine, s); err != nil {
		return err
	}
	if err := Convert_config_ShootWorkerVolumeConfiguration_To_v1alpha1_ShootWorkerVolumeConfiguration(&in.Volume, &out.Volume, s); err != nil {
		return err
	}
	out.Minimum = (*int32)(unsafe.Pointer(in.Minimum))
	out.Maximum = (*int32)(unsafe.Pointer(in.Maximum))
	out.MaxSurge = (*int32)(unsafe.Pointer(in.MaxSurge))
	out.MaxUnavailable = (*int32)(unsafe.Pointer(in.MaxUnavailable))
	return nil
}

// Convert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration is an autogenerated conversion function.
func Convert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration(in *config.ShootWorkersConfiguration, out *ShootWorkersConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootWorkersConfiguration_To_v1alpha1_ShootWorkersConfiguration(in, out, s)
}
