apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: name
    required: true
    type: data
    schema:
      type: string

  - name: plan
    required: true
    type: data
    schema:
      type: string

  - name: serviceInstanceParameters
    required: false
    schema:
      type: object
      properties: {}

  - name: serviceBindingParameters
    required: false
    schema:
      type: object
      properties: {}

  - name: btpOperatorReady
    required: true
    type: data
    schema:
      type: boolean

exports:
  - name: fluentdEndpoint
    type: data
    schema:
      type: string

  - name: fluentdUsername
    type: data
    schema:
      type: string

  - name: fluentdPassword
    type: data
    schema:
      type: string

  - name: kibanaEndpoint
    type: data
    schema:
      type: string

  - name: kibanaUsername
    type: data
    schema:
      type: string

  - name: kibanaPassword
    type: data
    schema:
      type: string

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate
