apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: shootCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: targetClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: shootConfig
    type: data
    schema:
      description: |
        The "shootConfig" Specifies the gardener shoot configuration.
      $ref: "cd://resources/shoot-config-definition"

  - name: rotationConfig
    type: data
    schema:
      description: |
        The configuration for the rotation of credentials.
      $ref: "cd://resources/rotation-config-definition"

exports:
  - name: landscaperControllerKubeconfigYaml
    type: data
    schema:
      type: string

  - name: landscaperWebhooksKubeconfigYaml
    type: data
    schema:
      type: string

  - name: landscaperUserKubeconfigYaml
    type: data
    schema:
      type: string

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
