//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityMonitoringConfiguration) DeepCopyInto(out *AvailabilityMonitoringConfiguration) {
	*out = *in
	out.AvailabilityServiceConfiguration = in.AvailabilityServiceConfiguration
	out.PeriodicCheckInterval = in.PeriodicCheckInterval
	out.LSHealthCheckTimeout = in.LSHealthCheckTimeout
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityMonitoringConfiguration.
func (in *AvailabilityMonitoringConfiguration) DeepCopy() *AvailabilityMonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(AvailabilityMonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityServiceConfiguration) DeepCopyInto(out *AvailabilityServiceConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityServiceConfiguration.
func (in *AvailabilityServiceConfiguration) DeepCopy() *AvailabilityServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(AvailabilityServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrdManagementConfiguration) DeepCopyInto(out *CrdManagementConfiguration) {
	*out = *in
	if in.DeployCustomResourceDefinitions != nil {
		in, out := &in.DeployCustomResourceDefinitions, &out.DeployCustomResourceDefinitions
		*out = new(bool)
		**out = **in
	}
	if in.ForceUpdate != nil {
		in, out := &in.ForceUpdate, &out.ForceUpdate
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrdManagementConfiguration.
func (in *CrdManagementConfiguration) DeepCopy() *CrdManagementConfiguration {
	if in == nil {
		return nil
	}
	out := new(CrdManagementConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperServiceComponentConfiguration) DeepCopyInto(out *LandscaperServiceComponentConfiguration) {
	*out = *in
	in.RepositoryContext.DeepCopyInto(&out.RepositoryContext)
	if in.RegistryPullSecrets != nil {
		in, out := &in.RegistryPullSecrets, &out.RegistryPullSecrets
		*out = make([]v1.SecretReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperServiceComponentConfiguration.
func (in *LandscaperServiceComponentConfiguration) DeepCopy() *LandscaperServiceComponentConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscaperServiceComponentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperServiceConfiguration) DeepCopyInto(out *LandscaperServiceConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfiguration)
		**out = **in
	}
	out.AvailabilityMonitoring = in.AvailabilityMonitoring
	in.CrdManagement.DeepCopyInto(&out.CrdManagement)
	in.LandscaperServiceComponent.DeepCopyInto(&out.LandscaperServiceComponent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperServiceConfiguration.
func (in *LandscaperServiceConfiguration) DeepCopy() *LandscaperServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscaperServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscaperServiceConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfiguration) DeepCopyInto(out *MetricsConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfiguration.
func (in *MetricsConfiguration) DeepCopy() *MetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(MetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}
