{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.controller.clusterRoleName }}
  labels:
      {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.controller.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.webhooksServer.clusterRoleName }}
  labels:
      {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.webhooksServer.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.webhooksServer.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.user.clusterRoleName }}
  labels:
      {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.user.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.user.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
...
