{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.controller.clusterRoleName }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - "*"
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - watch
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - "*"
