{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "landscaper.clusterrole.name" . }}
  labels:
      {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "landscaper.clusterrole.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
