{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.landscaper.name }}-controller-cluster-kubeconfig
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  kubeconfig: {{ .Values.controller.resourceCluster.kubeconfig | b64enc }}
...
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.landscaper.name }}-webhooks-cluster-kubeconfig
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  kubeconfig: {{ .Values.webhooksServer.resourceCluster.kubeconfig | b64enc }}
...