apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

localTypes:
  registryPullSecrets:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
      required:
        - name
        - namespace

imports:
  - name: targetCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: verbosity
    required: true
    type: data
    schema:
      type: string

  - name: availabilityMonitoring
    required: false
    type: data
    schema:
      type: object
      properties:
        selfLandscaperNamespace:
          type: string
        periodicCheckInterval:
          type: string
        lsHealthCheckTimeout:
          type: string

  - name: AVSConfiguration
    required: false
    type: data
    schema:
      type: object
      properties:
        url:
          type: string
        apiKey:
          type: string
        timeout:
          type: string

  - name: registryPullSecrets
    required: false
    type: data
    schema:
      $ref: "local://registryPullSecrets"

  - name: gardenerConfiguration
    required: true
    type: data
    schema:
      type: object
      properties:
        serviceAccountKubeconfig:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
            key:
              type: string
        projectName:
          type: string

  - name: auditLogConfiguration
    required: false
    type: data
    schema:
      type: object
      properties:
        subaccountId:
          type: string

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate