#!/bin/bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

echo "component-cli is required to generate the component descriptors"
CLI_PATH="$(mktemp -d)"
COMP_CLI=${CLI_PATH}/component-cli
echo "Trying to installing component-cli to ${COMP_CLI}"
curl -L https://github.com/gardener/component-cli/releases/download/v0.48.0/componentcli-linux-amd64.gz | gzip -d > ${COMP_CLI}
chmod +x ${COMP_CLI}

SOURCE_PATH="$(dirname $0)/.."
VERSION="$(${SOURCE_PATH}/hack/get-version.sh)"
COMMIT_SHA="$(git --git-dir ${SOURCE_PATH}/.git rev-parse HEAD)"
REPO_CTX="${CURRENT_COMPONENT_REPOSITORY}"

CTF_PATH="ctf-path"

printf "> Building components with version ${VERSION} - ${COMMIT_SHA}\n"

function buildResourcesArgs()  {
  PATH=$1
  FILES=$2
  RESOURCES=""

  for file in $FILES; do
    if [[ -z $RESOURCES ]]; then
      RESOURCES+="-r ${PATH}/$file"
    else
      RESOURCES+=" -r ${PATH}/$file"
    fi
  done

  echo $RESOURCES
}

function buildComponentArchive() {
  COMPONENT_NAME=$1
  RESOURCES=$2
  CA_PATH="$(mktemp -d)"
  printf "> Building component ${COMPONENT_NAME}\n"

  COMPONENT_REFERENCES=""

  if [ -f ${SOURCE_PATH}/.landscaper/${COMPONENT_NAME}/component-references.yaml ]; then
    COMPONENT_REFERENCES="-c ${SOURCE_PATH}/.landscaper/${COMPONENT_NAME}/component-references.yaml"
  fi

  RESOURCES_ARGS=$(buildResourcesArgs "${SOURCE_PATH}/.landscaper/${COMPONENT_NAME}" "${RESOURCES}")

  ${COMP_CLI} ca "${CA_PATH}" "${CTF_PATH}" \
    --component-name=github.com/gardener/landscaper-service/${COMPONENT_NAME} \
    --component-version=${VERSION} \
    --repo-ctx=${REPO_CTX} \
    -s ${SOURCE_PATH}/.landscaper/sources.yaml \
    ${RESOURCES_ARGS} \
    COMMIT_SHA=${COMMIT_SHA} \
    VERSION=${VERSION} \
    $COMPONENT_REFERENCES
}

buildComponentArchive "logging-stack" "resources.yaml resources-cert-manager.yaml resources-sap-btp-service-operator.yaml resources-fluentbit.yaml"
buildComponentArchive "ingress-controller" "resources.yaml"
buildComponentArchive "landscaper-instance" "resources.yaml"

# add landscaper component descriptor
printf "> Create Landscaper Service ca archive\n"
LS_CA_PATH="$(mktemp -d)"
cp ${BASE_DEFINITION_PATH} "${LS_CA_PATH}/component-descriptor.yaml"

printf "> add resources\n"
${COMP_CLI} ca resources add ${LS_CA_PATH} \
    VERSION=${VERSION} \
    ${SOURCE_PATH}/.landscaper/resources.yaml

printf "> add component references\n"
${COMP_CLI} ca component-references add ${LS_CA_PATH} \
    VERSION=${VERSION} \
    ${SOURCE_PATH}/.landscaper/component-references.yaml

cat ${LS_CA_PATH}/component-descriptor.yaml

printf "> Add Landscaper Service CA to ctf\n"
${COMP_CLI} ctf add "${CTF_PATH}" -f "${LS_CA_PATH}"

# also upload the components to a open source repo
# todo: remove as soon as the default component repository is public
${COMP_CLI} ctf push --repo-ctx="eu.gcr.io/gardener-project/development" "${CTF_PATH}"
