#!/bin/sh

PROJECT_ROOT="$(dirname $0)/.."

echo "check if integration tests should be started"
(
  if ! which git 1>/dev/null; then
    echo "Installing git... "
    apk add --no-cache --no-progress git
  fi

  cd "${PROJECT_ROOT}"
  PROJECT_ROOT="$(pwd)"

  GIT_COMMENT=$(git show -s --format=%s)
  echo "git comment: " $GIT_COMMENT

  if git show -s --format=%s | grep run-int-tests; then
    echo "'run-int-tests' in commit message, integration tests should be started"
    ${PROJECT_ROOT}/hack/integration-test.sh pull-request
  elif git branch --show-current | grep -E "renovate/|dependabot/"; then
    echo "Dependency update from renovate, integration tests should be started"
    ${PROJECT_ROOT}/hack/integration-test.sh pull-request
  else
    echo "integration tests are skipped"
  fi
)