#!/bin/bash

# SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."
CHART_REPO="eu.gcr.io/gardener-project/landscaper-service/charts/"

${SOURCE_PATH}/hack/update-helm-chart-version.sh

$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-service
