#!/bin/bash

# SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."
CHART_REPO="eu.gcr.io/gardener-project/landscaper-service/charts/"

${SOURCE_PATH}/hack/update-helm-chart-version.sh

$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-service
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-service-target-shoot-sidecar-server
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/sidecar-rbac

CHART_REPO="eu.gcr.io/gardener-project/landscaper-service/charts/landscaper-instance/resource-cluster"

$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/resource-cluster/landscaper
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/resource-cluster/deployer

CHART_REPO="eu.gcr.io/gardener-project/landscaper-service/charts/landscaper-instance/target-cluster"

$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/target-cluster/landscaper
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/target-cluster/helm-deployer
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/target-cluster/manifest-deployer
$SOURCE_PATH/hack/create-helm-chart.sh ${CHART_REPO} charts/landscaper-instance/target-cluster/container-deployer
