#!/bin/bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

SOURCE_DIR="$(realpath $(dirname $0)/..)"

source "$SOURCE_DIR/.ci/ensure-go"
"$SOURCE_DIR/.ci/ensure-make"

apk add --no-cache git musl-dev curl
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

cd $SOURCE_DIR
make revendor

# the helm chart versions need to be updated in the release step to reflect the change in the Git repository
${SOURCE_DIR}/hack/update-helm-chart-version.sh
