#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"

(
  cd "${PROJECT_ROOT}"

  make revendor
  SKIP_FORMATTING_CHECK=true make verify # code formatting happens during head-update pipeline step, no need to verify it here
  make test
)
