apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: fluentbitClusters
    required: true
    type: targetList
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: fluentdEndpoint
    required: true
    type: data
    schema:
      type: string

  - name: fluentdUsername
    required: true
    type: data
    schema:
      type: string

  - name: fluentdPassword
    required: true
    type: data
    schema:
      type: string

  - name: kubernetesInputPath
    required: true
    type: data
    schema:
      type: string

  - name: kubernetesExcludePath
    required: true
    type: data
    schema:
      type: string

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
