//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package provisioning

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticReconcile) DeepCopyInto(out *AutomaticReconcile) {
	*out = *in
	out.Interval = in.Interval
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticReconcile.
func (in *AutomaticReconcile) DeepCopy() *AutomaticReconcile {
	if in == nil {
		return nil
	}
	out := new(AutomaticReconcile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityCollection) DeepCopyInto(out *AvailabilityCollection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityCollection.
func (in *AvailabilityCollection) DeepCopy() *AvailabilityCollection {
	if in == nil {
		return nil
	}
	out := new(AvailabilityCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityCollection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityCollectionList) DeepCopyInto(out *AvailabilityCollectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvailabilityCollection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityCollectionList.
func (in *AvailabilityCollectionList) DeepCopy() *AvailabilityCollectionList {
	if in == nil {
		return nil
	}
	out := new(AvailabilityCollectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityCollectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityCollectionSpec) DeepCopyInto(out *AvailabilityCollectionSpec) {
	*out = *in
	if in.InstanceRefs != nil {
		in, out := &in.InstanceRefs, &out.InstanceRefs
		*out = make([]ObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityCollectionSpec.
func (in *AvailabilityCollectionSpec) DeepCopy() *AvailabilityCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(AvailabilityCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityCollectionStatus) DeepCopyInto(out *AvailabilityCollectionStatus) {
	*out = *in
	in.LastRun.DeepCopyInto(&out.LastRun)
	in.LastReported.DeepCopyInto(&out.LastReported)
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]AvailabilityInstance, len(*in))
		copy(*out, *in)
	}
	out.Self = in.Self
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityCollectionStatus.
func (in *AvailabilityCollectionStatus) DeepCopy() *AvailabilityCollectionStatus {
	if in == nil {
		return nil
	}
	out := new(AvailabilityCollectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityInstance) DeepCopyInto(out *AvailabilityInstance) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityInstance.
func (in *AvailabilityInstance) DeepCopy() *AvailabilityInstance {
	if in == nil {
		return nil
	}
	out := new(AvailabilityInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Controller) DeepCopyInto(out *Controller) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Controller.
func (in *Controller) DeepCopy() *Controller {
	if in == nil {
		return nil
	}
	out := new(Controller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Controllers) DeepCopyInto(out *Controllers) {
	*out = *in
	if in.Installations != nil {
		in, out := &in.Installations, &out.Installations
		*out = new(Controller)
		**out = **in
	}
	if in.Executions != nil {
		in, out := &in.Executions, &out.Executions
		*out = new(Controller)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Controllers.
func (in *Controllers) DeepCopy() *Controllers {
	if in == nil {
		return nil
	}
	out := new(Controllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPlane) DeepCopyInto(out *DataPlane) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPlane.
func (in *DataPlane) DeepCopy() *DataPlane {
	if in == nil {
		return nil
	}
	out := new(DataPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployItemTimeouts) DeepCopyInto(out *DeployItemTimeouts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployItemTimeouts.
func (in *DeployItemTimeouts) DeepCopy() *DeployItemTimeouts {
	if in == nil {
		return nil
	}
	out := new(DeployItemTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployer) DeepCopyInto(out *Deployer) {
	*out = *in
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(Controller)
		**out = **in
	}
	if in.K8SClientSettings != nil {
		in, out := &in.K8SClientSettings, &out.K8SClientSettings
		*out = new(K8SClientSettings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployer.
func (in *Deployer) DeepCopy() *Deployer {
	if in == nil {
		return nil
	}
	out := new(Deployer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployerConfig) DeepCopyInto(out *DeployerConfig) {
	*out = *in
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(Deployer)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		**out = **in
	}
	if in.HPA != nil {
		in, out := &in.HPA, &out.HPA
		*out = new(HPA)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployerConfig.
func (in *DeployerConfig) DeepCopy() *DeployerConfig {
	if in == nil {
		return nil
	}
	out := new(DeployerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Error) DeepCopyInto(out *Error) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Error.
func (in *Error) DeepCopy() *Error {
	if in == nil {
		return nil
	}
	out := new(Error)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPA) DeepCopyInto(out *HPA) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPA.
func (in *HPA) DeepCopy() *HPA {
	if in == nil {
		return nil
	}
	out := new(HPA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	in.LandscaperConfiguration.DeepCopyInto(&out.LandscaperConfiguration)
	out.ServiceTargetConfigRef = in.ServiceTargetConfigRef
	if in.AutomaticReconcile != nil {
		in, out := &in.AutomaticReconcile, &out.AutomaticReconcile
		*out = new(AutomaticReconcile)
		**out = **in
	}
	in.DataPlane.DeepCopyInto(&out.DataPlane)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(Error)
		(*in).DeepCopyInto(*out)
	}
	if in.LandscaperServiceComponent != nil {
		in, out := &in.LandscaperServiceComponent, &out.LandscaperServiceComponent
		*out = new(LandscaperServiceComponent)
		**out = **in
	}
	if in.ContextRef != nil {
		in, out := &in.ContextRef, &out.ContextRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.DataPlaneClusterRef != nil {
		in, out := &in.DataPlaneClusterRef, &out.DataPlaneClusterRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.InstallationRef != nil {
		in, out := &in.InstallationRef, &out.InstallationRef
		*out = new(ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8SClientLimits) DeepCopyInto(out *K8SClientLimits) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SClientLimits.
func (in *K8SClientLimits) DeepCopy() *K8SClientLimits {
	if in == nil {
		return nil
	}
	out := new(K8SClientLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8SClientSettings) DeepCopyInto(out *K8SClientSettings) {
	*out = *in
	if in.HostClient != nil {
		in, out := &in.HostClient, &out.HostClient
		*out = new(K8SClientLimits)
		**out = **in
	}
	if in.ResourceClient != nil {
		in, out := &in.ResourceClient, &out.ResourceClient
		*out = new(K8SClientLimits)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SClientSettings.
func (in *K8SClientSettings) DeepCopy() *K8SClientSettings {
	if in == nil {
		return nil
	}
	out := new(K8SClientSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Landscaper) DeepCopyInto(out *Landscaper) {
	*out = *in
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = new(Controllers)
		(*in).DeepCopyInto(*out)
	}
	if in.K8SClientSettings != nil {
		in, out := &in.K8SClientSettings, &out.K8SClientSettings
		*out = new(K8SClientSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.DeployItemTimeouts != nil {
		in, out := &in.DeployItemTimeouts, &out.DeployItemTimeouts
		*out = new(DeployItemTimeouts)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Landscaper.
func (in *Landscaper) DeepCopy() *Landscaper {
	if in == nil {
		return nil
	}
	out := new(Landscaper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperConfiguration) DeepCopyInto(out *LandscaperConfiguration) {
	*out = *in
	if in.Landscaper != nil {
		in, out := &in.Landscaper, &out.Landscaper
		*out = new(Landscaper)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		**out = **in
	}
	if in.ResourcesMain != nil {
		in, out := &in.ResourcesMain, &out.ResourcesMain
		*out = new(Resources)
		**out = **in
	}
	if in.HPAMain != nil {
		in, out := &in.HPAMain, &out.HPAMain
		*out = new(HPA)
		**out = **in
	}
	if in.Deployers != nil {
		in, out := &in.Deployers, &out.Deployers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeployersConfig != nil {
		in, out := &in.DeployersConfig, &out.DeployersConfig
		*out = make(map[string]*DeployerConfig, len(*in))
		for key, val := range *in {
			var outVal *DeployerConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(DeployerConfig)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperConfiguration.
func (in *LandscaperConfiguration) DeepCopy() *LandscaperConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscaperConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperDeployment) DeepCopyInto(out *LandscaperDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperDeployment.
func (in *LandscaperDeployment) DeepCopy() *LandscaperDeployment {
	if in == nil {
		return nil
	}
	out := new(LandscaperDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscaperDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperDeploymentList) DeepCopyInto(out *LandscaperDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LandscaperDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperDeploymentList.
func (in *LandscaperDeploymentList) DeepCopy() *LandscaperDeploymentList {
	if in == nil {
		return nil
	}
	out := new(LandscaperDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscaperDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperDeploymentSpec) DeepCopyInto(out *LandscaperDeploymentSpec) {
	*out = *in
	in.LandscaperConfiguration.DeepCopyInto(&out.LandscaperConfiguration)
	in.DataPlane.DeepCopyInto(&out.DataPlane)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperDeploymentSpec.
func (in *LandscaperDeploymentSpec) DeepCopy() *LandscaperDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(LandscaperDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperDeploymentStatus) DeepCopyInto(out *LandscaperDeploymentStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(Error)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceRef != nil {
		in, out := &in.InstanceRef, &out.InstanceRef
		*out = new(ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperDeploymentStatus.
func (in *LandscaperDeploymentStatus) DeepCopy() *LandscaperDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(LandscaperDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperServiceComponent) DeepCopyInto(out *LandscaperServiceComponent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperServiceComponent.
func (in *LandscaperServiceComponent) DeepCopy() *LandscaperServiceComponent {
	if in == nil {
		return nil
	}
	out := new(LandscaperServiceComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequests) DeepCopyInto(out *ResourceRequests) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequests.
func (in *ResourceRequests) DeepCopy() *ResourceRequests {
	if in == nil {
		return nil
	}
	out := new(ResourceRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	out.Requests = in.Requests
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	out.ObjectReference = in.ObjectReference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTargetConfig) DeepCopyInto(out *ServiceTargetConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTargetConfig.
func (in *ServiceTargetConfig) DeepCopy() *ServiceTargetConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceTargetConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTargetConfigList) DeepCopyInto(out *ServiceTargetConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceTargetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTargetConfigList.
func (in *ServiceTargetConfigList) DeepCopy() *ServiceTargetConfigList {
	if in == nil {
		return nil
	}
	out := new(ServiceTargetConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceTargetConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTargetConfigSpec) DeepCopyInto(out *ServiceTargetConfigSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTargetConfigSpec.
func (in *ServiceTargetConfigSpec) DeepCopy() *ServiceTargetConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceTargetConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTargetConfigStatus) DeepCopyInto(out *ServiceTargetConfigStatus) {
	*out = *in
	if in.InstanceRefs != nil {
		in, out := &in.InstanceRefs, &out.InstanceRefs
		*out = make([]ObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTargetConfigStatus.
func (in *ServiceTargetConfigStatus) DeepCopy() *ServiceTargetConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceTargetConfigStatus)
	in.DeepCopyInto(out)
	return out
}
