{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployer.clusterrole.name" . }}
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/status"
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - "serviceaccounts"
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - get
      - list
      - watch
