{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployer.name }}-config
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "deployer-config" . | b64enc }}
