{{/* SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sidecar.serviceAccountName" . }}
  labels:
    {{- include "sidecar.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "landscaper-service.gardener.cloud"
    resources:
      - "namespaceregistrations"
      - "namespaceregistrations/status"
      - "subjectlists"
      - "subjectlists/status"
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - '*'
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - '*'
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
    verbs:
      - '*'
