{{/* SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sidecar.serviceAccountName" . }}
  labels:
    {{- include "sidecar.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
