apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: landscaper-deployment

blueprint:
  ref: cd://resources/landscaper-blueprint

imports:
  targets:
    - name: targetCluster
      target: targetCluster
  data:
    - name: targetClusterNamespace
      dataRef: targetClusterNamespace
    - name: dataPlaneClusterNamespace
      dataRef: dataPlaneClusterNamespace
    - name: landscaperControllerKubeconfigYaml
      dataRef: landscaperControllerKubeconfigYaml
    - name: landscaperWebhooksKubeconfigYaml
      dataRef: landscaperWebhooksKubeconfigYaml
    - name: registryConfig
      dataRef: registryConfig
    - name: landscaperConfig
      dataRef: landscaperConfig
    - name: webhooksHostName
      dataRef: webhooksHostName
