apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: sidecar-server

blueprint:
  ref: cd://resources/sidecar-blueprint

imports:
  targets:
    - name: targetCluster
      target: targetCluster
  data:
    - name: targetClusterNamespace
      dataRef: targetClusterNamespace
    - name: landscaperControllerKubeconfigYaml
      dataRef: sidecarControllerKubeconfigYaml
    - name: sidecarConfig
      dataRef: sidecarConfig
