{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName }}
  labels:
    {{- include "deployer.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - deployitems
      - deployitems/status
    verbs:
      - get
      - watch
      - list
      - update
      - patch

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - targets
      - contexts
    verbs:
      - get
      - watch
      - list

  - apiGroups:
      - landscaper.gardener.cloud
    resources:
      - syncobjects
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - watch
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"