{{/* SPDX-FileCopyrightText: 2023 "SAP SE or an SAP affiliate company and Gardener contributors"

  SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.controller.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ls-service-target-shoot-sidecar.controller.serviceAccountName" . }}
  labels:
    {{- include "ls-service-target-shoot-sidecar.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "*"
  - apiGroups:
      - "landscaper-service.gardener.cloud"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "landscaper.gardener.cloud"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
    - ""
    resources:
      - "secrets"
      - "configmaps"
    verbs:
      - "*"
{{- end }}
