{{/* SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ls-service-target-shoot-sidecar.fullname" . }}-config
  labels:
    {{- include "ls-service-target-shoot-sidecar.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "ls-service-target-shoot-sidecar-config" . | b64enc }}
