{{/* SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ls-service-target-shoot-sidecar.fullname" . }}-controller-cluster-kubeconfig
  labels:
    {{- include "ls-service-target-shoot-sidecar.labels" . | nindent 4 }}
data:
  kubeconfig: {{ .Values.controller.kubeconfig | b64enc }}
