{{/* SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"

  SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ls-service-target-shoot-sidecar.fullname" . }}
  labels:
    {{- include "ls-service-target-shoot-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "ls-service-target-shoot-sidecar.selectorLabels" . | nindent 4 }}
