apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: targetClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: landscaperControllerKubeconfigYaml
    required: true
    type: data
    schema:
      type: string

  - name: sidecarConfig
    type: data
    schema:
      $ref: "cd://resources/sidecar-config-definition"

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
