apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: hostingCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: hostingClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: landscaperControllerKubeconfigYaml
    required: true
    type: data
    schema:
      type: string

  - name: verbosity
    required: true
    type: data
    schema:
      type: string
    
  - name: webhooksHostName
    required: true
    type: data
    schema:
      type: string

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
