apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: sidecar-rbac

blueprint:
  ref: cd://resources/sidecar-rbac-blueprint

imports:
  targets:
    - name: shootCluster
      target: dataPlaneCluster
  data:
    - name: targetClusterNamespace
      dataRef: dataPlaneClusterNamespace
    - name: rotationConfig
      dataRef: rotationConfig

exports:
  data:
    - name: sidecarControllerKubeconfigYaml
      dataRef: sidecarControllerKubeconfigYaml
