# SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"
#
# SPDX-License-Identifier: Apache-2.0

landscaperservice:
  verbosity: 2

  #  metrics:
  #    port: 8080

  crdManagement:
    deployCrd: true
  #   forceUpdate: true

image: {}

controller:
  replicaCount: 1
  image:
    repository: eu.gcr.io/gardener-project/landscaper-service/landscaper-service-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the .Values.image.tag or chart appVersion.
    #tag: ""

webhooksServer:
  replicaCount: 1
  image:
    repository: eu.gcr.io/gardener-project/landscaper-service/landscaper-service-webhooks-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the .Values.image.tag or the chart appVersion.
    #tag: ""

  servicePort: 9443 # required unless disableWebhooks contains "all"
  disableWebhooks: [ ] # options: landscaperdeployments, instances, servicetargetconfigs, all
  # Specify the namespace where the webhooks server certificate secret is stored.
  certificatesNamespace: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  controller:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, the default will be "landscaper-service"
    name: ""
  webhooksServer:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, the default will be "landscaper-service-webhooks"
    name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
