# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: helm-deployer
description: Landscaper Helm Deployer
type: application
version: v0.1.0
appVersion: v0.77.0
