//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	core "github.com/gardener/landscaper-service/pkg/apis/core"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AutomaticReconcile)(nil), (*core.AutomaticReconcile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AutomaticReconcile_To_core_AutomaticReconcile(a.(*AutomaticReconcile), b.(*core.AutomaticReconcile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AutomaticReconcile)(nil), (*AutomaticReconcile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AutomaticReconcile_To_v1alpha2_AutomaticReconcile(a.(*core.AutomaticReconcile), b.(*AutomaticReconcile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityCollection)(nil), (*core.AvailabilityCollection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilityCollection_To_core_AvailabilityCollection(a.(*AvailabilityCollection), b.(*core.AvailabilityCollection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AvailabilityCollection)(nil), (*AvailabilityCollection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AvailabilityCollection_To_v1alpha2_AvailabilityCollection(a.(*core.AvailabilityCollection), b.(*AvailabilityCollection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityCollectionList)(nil), (*core.AvailabilityCollectionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilityCollectionList_To_core_AvailabilityCollectionList(a.(*AvailabilityCollectionList), b.(*core.AvailabilityCollectionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AvailabilityCollectionList)(nil), (*AvailabilityCollectionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AvailabilityCollectionList_To_v1alpha2_AvailabilityCollectionList(a.(*core.AvailabilityCollectionList), b.(*AvailabilityCollectionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityCollectionSpec)(nil), (*core.AvailabilityCollectionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec(a.(*AvailabilityCollectionSpec), b.(*core.AvailabilityCollectionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AvailabilityCollectionSpec)(nil), (*AvailabilityCollectionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec(a.(*core.AvailabilityCollectionSpec), b.(*AvailabilityCollectionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityCollectionStatus)(nil), (*core.AvailabilityCollectionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus(a.(*AvailabilityCollectionStatus), b.(*core.AvailabilityCollectionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AvailabilityCollectionStatus)(nil), (*AvailabilityCollectionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus(a.(*core.AvailabilityCollectionStatus), b.(*AvailabilityCollectionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AvailabilityInstance)(nil), (*core.AvailabilityInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance(a.(*AvailabilityInstance), b.(*core.AvailabilityInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AvailabilityInstance)(nil), (*AvailabilityInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance(a.(*core.AvailabilityInstance), b.(*AvailabilityInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Controller)(nil), (*core.Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Controller_To_core_Controller(a.(*Controller), b.(*core.Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Controller)(nil), (*Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Controller_To_v1alpha2_Controller(a.(*core.Controller), b.(*Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Controllers)(nil), (*core.Controllers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Controllers_To_core_Controllers(a.(*Controllers), b.(*core.Controllers), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Controllers)(nil), (*Controllers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Controllers_To_v1alpha2_Controllers(a.(*core.Controllers), b.(*Controllers), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataPlane)(nil), (*core.DataPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DataPlane_To_core_DataPlane(a.(*DataPlane), b.(*core.DataPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DataPlane)(nil), (*DataPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DataPlane_To_v1alpha2_DataPlane(a.(*core.DataPlane), b.(*DataPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployItemTimeouts)(nil), (*core.DeployItemTimeouts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DeployItemTimeouts_To_core_DeployItemTimeouts(a.(*DeployItemTimeouts), b.(*core.DeployItemTimeouts), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployItemTimeouts)(nil), (*DeployItemTimeouts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployItemTimeouts_To_v1alpha2_DeployItemTimeouts(a.(*core.DeployItemTimeouts), b.(*DeployItemTimeouts), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Deployer)(nil), (*core.Deployer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Deployer_To_core_Deployer(a.(*Deployer), b.(*core.Deployer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Deployer)(nil), (*Deployer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Deployer_To_v1alpha2_Deployer(a.(*core.Deployer), b.(*Deployer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployerConfig)(nil), (*core.DeployerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DeployerConfig_To_core_DeployerConfig(a.(*DeployerConfig), b.(*core.DeployerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployerConfig)(nil), (*DeployerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployerConfig_To_v1alpha2_DeployerConfig(a.(*core.DeployerConfig), b.(*DeployerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Error)(nil), (*core.Error)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Error_To_core_Error(a.(*Error), b.(*core.Error), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Error)(nil), (*Error)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Error_To_v1alpha2_Error(a.(*core.Error), b.(*Error), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HPA)(nil), (*core.HPA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HPA_To_core_HPA(a.(*HPA), b.(*core.HPA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.HPA)(nil), (*HPA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_HPA_To_v1alpha2_HPA(a.(*core.HPA), b.(*HPA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Instance)(nil), (*core.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Instance_To_core_Instance(a.(*Instance), b.(*core.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Instance)(nil), (*Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Instance_To_v1alpha2_Instance(a.(*core.Instance), b.(*Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceList)(nil), (*core.InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceList_To_core_InstanceList(a.(*InstanceList), b.(*core.InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.InstanceList)(nil), (*InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_InstanceList_To_v1alpha2_InstanceList(a.(*core.InstanceList), b.(*InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceSpec)(nil), (*core.InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceSpec_To_core_InstanceSpec(a.(*InstanceSpec), b.(*core.InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.InstanceSpec)(nil), (*InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_InstanceSpec_To_v1alpha2_InstanceSpec(a.(*core.InstanceSpec), b.(*InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceStatus)(nil), (*core.InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceStatus_To_core_InstanceStatus(a.(*InstanceStatus), b.(*core.InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.InstanceStatus)(nil), (*InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_InstanceStatus_To_v1alpha2_InstanceStatus(a.(*core.InstanceStatus), b.(*InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8SClientLimits)(nil), (*core.K8SClientLimits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_K8SClientLimits_To_core_K8SClientLimits(a.(*K8SClientLimits), b.(*core.K8SClientLimits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.K8SClientLimits)(nil), (*K8SClientLimits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_K8SClientLimits_To_v1alpha2_K8SClientLimits(a.(*core.K8SClientLimits), b.(*K8SClientLimits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8SClientSettings)(nil), (*core.K8SClientSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_K8SClientSettings_To_core_K8SClientSettings(a.(*K8SClientSettings), b.(*core.K8SClientSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.K8SClientSettings)(nil), (*K8SClientSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_K8SClientSettings_To_v1alpha2_K8SClientSettings(a.(*core.K8SClientSettings), b.(*K8SClientSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Landscaper)(nil), (*core.Landscaper)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Landscaper_To_core_Landscaper(a.(*Landscaper), b.(*core.Landscaper), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Landscaper)(nil), (*Landscaper)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Landscaper_To_v1alpha2_Landscaper(a.(*core.Landscaper), b.(*Landscaper), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperConfiguration)(nil), (*core.LandscaperConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(a.(*LandscaperConfiguration), b.(*core.LandscaperConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperConfiguration)(nil), (*LandscaperConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(a.(*core.LandscaperConfiguration), b.(*LandscaperConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperDeployment)(nil), (*core.LandscaperDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperDeployment_To_core_LandscaperDeployment(a.(*LandscaperDeployment), b.(*core.LandscaperDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperDeployment)(nil), (*LandscaperDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperDeployment_To_v1alpha2_LandscaperDeployment(a.(*core.LandscaperDeployment), b.(*LandscaperDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperDeploymentList)(nil), (*core.LandscaperDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperDeploymentList_To_core_LandscaperDeploymentList(a.(*LandscaperDeploymentList), b.(*core.LandscaperDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperDeploymentList)(nil), (*LandscaperDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperDeploymentList_To_v1alpha2_LandscaperDeploymentList(a.(*core.LandscaperDeploymentList), b.(*LandscaperDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperDeploymentSpec)(nil), (*core.LandscaperDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec(a.(*LandscaperDeploymentSpec), b.(*core.LandscaperDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperDeploymentSpec)(nil), (*LandscaperDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec(a.(*core.LandscaperDeploymentSpec), b.(*LandscaperDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperDeploymentStatus)(nil), (*core.LandscaperDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus(a.(*LandscaperDeploymentStatus), b.(*core.LandscaperDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperDeploymentStatus)(nil), (*LandscaperDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus(a.(*core.LandscaperDeploymentStatus), b.(*LandscaperDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscaperServiceComponent)(nil), (*core.LandscaperServiceComponent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LandscaperServiceComponent_To_core_LandscaperServiceComponent(a.(*LandscaperServiceComponent), b.(*core.LandscaperServiceComponent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscaperServiceComponent)(nil), (*LandscaperServiceComponent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscaperServiceComponent_To_v1alpha2_LandscaperServiceComponent(a.(*core.LandscaperServiceComponent), b.(*LandscaperServiceComponent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceRegistration)(nil), (*core.NamespaceRegistration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NamespaceRegistration_To_core_NamespaceRegistration(a.(*NamespaceRegistration), b.(*core.NamespaceRegistration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamespaceRegistration)(nil), (*NamespaceRegistration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamespaceRegistration_To_v1alpha2_NamespaceRegistration(a.(*core.NamespaceRegistration), b.(*NamespaceRegistration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceRegistrationList)(nil), (*core.NamespaceRegistrationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NamespaceRegistrationList_To_core_NamespaceRegistrationList(a.(*NamespaceRegistrationList), b.(*core.NamespaceRegistrationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamespaceRegistrationList)(nil), (*NamespaceRegistrationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamespaceRegistrationList_To_v1alpha2_NamespaceRegistrationList(a.(*core.NamespaceRegistrationList), b.(*NamespaceRegistrationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceRegistrationSpec)(nil), (*core.NamespaceRegistrationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec(a.(*NamespaceRegistrationSpec), b.(*core.NamespaceRegistrationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamespaceRegistrationSpec)(nil), (*NamespaceRegistrationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec(a.(*core.NamespaceRegistrationSpec), b.(*NamespaceRegistrationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceRegistrationStatus)(nil), (*core.NamespaceRegistrationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus(a.(*NamespaceRegistrationStatus), b.(*core.NamespaceRegistrationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamespaceRegistrationStatus)(nil), (*NamespaceRegistrationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus(a.(*core.NamespaceRegistrationStatus), b.(*NamespaceRegistrationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectReference)(nil), (*core.ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ObjectReference_To_core_ObjectReference(a.(*ObjectReference), b.(*core.ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ObjectReference)(nil), (*ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ObjectReference_To_v1alpha2_ObjectReference(a.(*core.ObjectReference), b.(*ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceRequests)(nil), (*core.ResourceRequests)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ResourceRequests_To_core_ResourceRequests(a.(*ResourceRequests), b.(*core.ResourceRequests), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ResourceRequests)(nil), (*ResourceRequests)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ResourceRequests_To_v1alpha2_ResourceRequests(a.(*core.ResourceRequests), b.(*ResourceRequests), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Resources)(nil), (*core.Resources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Resources_To_core_Resources(a.(*Resources), b.(*core.Resources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Resources)(nil), (*Resources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Resources_To_v1alpha2_Resources(a.(*core.Resources), b.(*Resources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretReference)(nil), (*core.SecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SecretReference_To_core_SecretReference(a.(*SecretReference), b.(*core.SecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SecretReference)(nil), (*SecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SecretReference_To_v1alpha2_SecretReference(a.(*core.SecretReference), b.(*SecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceTargetConfig)(nil), (*core.ServiceTargetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ServiceTargetConfig_To_core_ServiceTargetConfig(a.(*ServiceTargetConfig), b.(*core.ServiceTargetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ServiceTargetConfig)(nil), (*ServiceTargetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ServiceTargetConfig_To_v1alpha2_ServiceTargetConfig(a.(*core.ServiceTargetConfig), b.(*ServiceTargetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceTargetConfigList)(nil), (*core.ServiceTargetConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ServiceTargetConfigList_To_core_ServiceTargetConfigList(a.(*ServiceTargetConfigList), b.(*core.ServiceTargetConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ServiceTargetConfigList)(nil), (*ServiceTargetConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ServiceTargetConfigList_To_v1alpha2_ServiceTargetConfigList(a.(*core.ServiceTargetConfigList), b.(*ServiceTargetConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceTargetConfigSpec)(nil), (*core.ServiceTargetConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec(a.(*ServiceTargetConfigSpec), b.(*core.ServiceTargetConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ServiceTargetConfigSpec)(nil), (*ServiceTargetConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec(a.(*core.ServiceTargetConfigSpec), b.(*ServiceTargetConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceTargetConfigStatus)(nil), (*core.ServiceTargetConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus(a.(*ServiceTargetConfigStatus), b.(*core.ServiceTargetConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ServiceTargetConfigStatus)(nil), (*ServiceTargetConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus(a.(*core.ServiceTargetConfigStatus), b.(*ServiceTargetConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subject)(nil), (*core.Subject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Subject_To_core_Subject(a.(*Subject), b.(*core.Subject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Subject)(nil), (*Subject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Subject_To_v1alpha2_Subject(a.(*core.Subject), b.(*Subject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubjectList)(nil), (*core.SubjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SubjectList_To_core_SubjectList(a.(*SubjectList), b.(*core.SubjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SubjectList)(nil), (*SubjectList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SubjectList_To_v1alpha2_SubjectList(a.(*core.SubjectList), b.(*SubjectList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubjectListList)(nil), (*core.SubjectListList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SubjectListList_To_core_SubjectListList(a.(*SubjectListList), b.(*core.SubjectListList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SubjectListList)(nil), (*SubjectListList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SubjectListList_To_v1alpha2_SubjectListList(a.(*core.SubjectListList), b.(*SubjectListList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubjectListSpec)(nil), (*core.SubjectListSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec(a.(*SubjectListSpec), b.(*core.SubjectListSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SubjectListSpec)(nil), (*SubjectListSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec(a.(*core.SubjectListSpec), b.(*SubjectListSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubjectListStatus)(nil), (*core.SubjectListStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus(a.(*SubjectListStatus), b.(*core.SubjectListStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SubjectListStatus)(nil), (*SubjectListStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus(a.(*core.SubjectListStatus), b.(*SubjectListStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_AutomaticReconcile_To_core_AutomaticReconcile(in *AutomaticReconcile, out *core.AutomaticReconcile, s conversion.Scope) error {
	out.Interval = in.Interval
	return nil
}

// Convert_v1alpha2_AutomaticReconcile_To_core_AutomaticReconcile is an autogenerated conversion function.
func Convert_v1alpha2_AutomaticReconcile_To_core_AutomaticReconcile(in *AutomaticReconcile, out *core.AutomaticReconcile, s conversion.Scope) error {
	return autoConvert_v1alpha2_AutomaticReconcile_To_core_AutomaticReconcile(in, out, s)
}

func autoConvert_core_AutomaticReconcile_To_v1alpha2_AutomaticReconcile(in *core.AutomaticReconcile, out *AutomaticReconcile, s conversion.Scope) error {
	out.Interval = in.Interval
	return nil
}

// Convert_core_AutomaticReconcile_To_v1alpha2_AutomaticReconcile is an autogenerated conversion function.
func Convert_core_AutomaticReconcile_To_v1alpha2_AutomaticReconcile(in *core.AutomaticReconcile, out *AutomaticReconcile, s conversion.Scope) error {
	return autoConvert_core_AutomaticReconcile_To_v1alpha2_AutomaticReconcile(in, out, s)
}

func autoConvert_v1alpha2_AvailabilityCollection_To_core_AvailabilityCollection(in *AvailabilityCollection, out *core.AvailabilityCollection, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AvailabilityCollection_To_core_AvailabilityCollection is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilityCollection_To_core_AvailabilityCollection(in *AvailabilityCollection, out *core.AvailabilityCollection, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilityCollection_To_core_AvailabilityCollection(in, out, s)
}

func autoConvert_core_AvailabilityCollection_To_v1alpha2_AvailabilityCollection(in *core.AvailabilityCollection, out *AvailabilityCollection, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_AvailabilityCollection_To_v1alpha2_AvailabilityCollection is an autogenerated conversion function.
func Convert_core_AvailabilityCollection_To_v1alpha2_AvailabilityCollection(in *core.AvailabilityCollection, out *AvailabilityCollection, s conversion.Scope) error {
	return autoConvert_core_AvailabilityCollection_To_v1alpha2_AvailabilityCollection(in, out, s)
}

func autoConvert_v1alpha2_AvailabilityCollectionList_To_core_AvailabilityCollectionList(in *AvailabilityCollectionList, out *core.AvailabilityCollectionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.AvailabilityCollection)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_AvailabilityCollectionList_To_core_AvailabilityCollectionList is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilityCollectionList_To_core_AvailabilityCollectionList(in *AvailabilityCollectionList, out *core.AvailabilityCollectionList, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilityCollectionList_To_core_AvailabilityCollectionList(in, out, s)
}

func autoConvert_core_AvailabilityCollectionList_To_v1alpha2_AvailabilityCollectionList(in *core.AvailabilityCollectionList, out *AvailabilityCollectionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AvailabilityCollection)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_AvailabilityCollectionList_To_v1alpha2_AvailabilityCollectionList is an autogenerated conversion function.
func Convert_core_AvailabilityCollectionList_To_v1alpha2_AvailabilityCollectionList(in *core.AvailabilityCollectionList, out *AvailabilityCollectionList, s conversion.Scope) error {
	return autoConvert_core_AvailabilityCollectionList_To_v1alpha2_AvailabilityCollectionList(in, out, s)
}

func autoConvert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec(in *AvailabilityCollectionSpec, out *core.AvailabilityCollectionSpec, s conversion.Scope) error {
	out.InstanceRefs = *(*[]core.ObjectReference)(unsafe.Pointer(&in.InstanceRefs))
	return nil
}

// Convert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec(in *AvailabilityCollectionSpec, out *core.AvailabilityCollectionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilityCollectionSpec_To_core_AvailabilityCollectionSpec(in, out, s)
}

func autoConvert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec(in *core.AvailabilityCollectionSpec, out *AvailabilityCollectionSpec, s conversion.Scope) error {
	out.InstanceRefs = *(*[]ObjectReference)(unsafe.Pointer(&in.InstanceRefs))
	return nil
}

// Convert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec is an autogenerated conversion function.
func Convert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec(in *core.AvailabilityCollectionSpec, out *AvailabilityCollectionSpec, s conversion.Scope) error {
	return autoConvert_core_AvailabilityCollectionSpec_To_v1alpha2_AvailabilityCollectionSpec(in, out, s)
}

func autoConvert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus(in *AvailabilityCollectionStatus, out *core.AvailabilityCollectionStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastRun = in.LastRun
	out.LastReported = in.LastReported
	out.Instances = *(*[]core.AvailabilityInstance)(unsafe.Pointer(&in.Instances))
	if err := Convert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance(&in.Self, &out.Self, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus(in *AvailabilityCollectionStatus, out *core.AvailabilityCollectionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilityCollectionStatus_To_core_AvailabilityCollectionStatus(in, out, s)
}

func autoConvert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus(in *core.AvailabilityCollectionStatus, out *AvailabilityCollectionStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastRun = in.LastRun
	out.LastReported = in.LastReported
	out.Instances = *(*[]AvailabilityInstance)(unsafe.Pointer(&in.Instances))
	if err := Convert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance(&in.Self, &out.Self, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus is an autogenerated conversion function.
func Convert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus(in *core.AvailabilityCollectionStatus, out *AvailabilityCollectionStatus, s conversion.Scope) error {
	return autoConvert_core_AvailabilityCollectionStatus_To_v1alpha2_AvailabilityCollectionStatus(in, out, s)
}

func autoConvert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance(in *AvailabilityInstance, out *core.AvailabilityInstance, s conversion.Scope) error {
	if err := Convert_v1alpha2_ObjectReference_To_core_ObjectReference(&in.ObjectReference, &out.ObjectReference, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.FailedReason = in.FailedReason
	return nil
}

// Convert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance(in *AvailabilityInstance, out *core.AvailabilityInstance, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilityInstance_To_core_AvailabilityInstance(in, out, s)
}

func autoConvert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance(in *core.AvailabilityInstance, out *AvailabilityInstance, s conversion.Scope) error {
	if err := Convert_core_ObjectReference_To_v1alpha2_ObjectReference(&in.ObjectReference, &out.ObjectReference, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.FailedReason = in.FailedReason
	return nil
}

// Convert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance is an autogenerated conversion function.
func Convert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance(in *core.AvailabilityInstance, out *AvailabilityInstance, s conversion.Scope) error {
	return autoConvert_core_AvailabilityInstance_To_v1alpha2_AvailabilityInstance(in, out, s)
}

func autoConvert_v1alpha2_Controller_To_core_Controller(in *Controller, out *core.Controller, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_v1alpha2_Controller_To_core_Controller is an autogenerated conversion function.
func Convert_v1alpha2_Controller_To_core_Controller(in *Controller, out *core.Controller, s conversion.Scope) error {
	return autoConvert_v1alpha2_Controller_To_core_Controller(in, out, s)
}

func autoConvert_core_Controller_To_v1alpha2_Controller(in *core.Controller, out *Controller, s conversion.Scope) error {
	out.Workers = in.Workers
	return nil
}

// Convert_core_Controller_To_v1alpha2_Controller is an autogenerated conversion function.
func Convert_core_Controller_To_v1alpha2_Controller(in *core.Controller, out *Controller, s conversion.Scope) error {
	return autoConvert_core_Controller_To_v1alpha2_Controller(in, out, s)
}

func autoConvert_v1alpha2_Controllers_To_core_Controllers(in *Controllers, out *core.Controllers, s conversion.Scope) error {
	out.Installations = (*core.Controller)(unsafe.Pointer(in.Installations))
	out.Executions = (*core.Controller)(unsafe.Pointer(in.Executions))
	return nil
}

// Convert_v1alpha2_Controllers_To_core_Controllers is an autogenerated conversion function.
func Convert_v1alpha2_Controllers_To_core_Controllers(in *Controllers, out *core.Controllers, s conversion.Scope) error {
	return autoConvert_v1alpha2_Controllers_To_core_Controllers(in, out, s)
}

func autoConvert_core_Controllers_To_v1alpha2_Controllers(in *core.Controllers, out *Controllers, s conversion.Scope) error {
	out.Installations = (*Controller)(unsafe.Pointer(in.Installations))
	out.Executions = (*Controller)(unsafe.Pointer(in.Executions))
	return nil
}

// Convert_core_Controllers_To_v1alpha2_Controllers is an autogenerated conversion function.
func Convert_core_Controllers_To_v1alpha2_Controllers(in *core.Controllers, out *Controllers, s conversion.Scope) error {
	return autoConvert_core_Controllers_To_v1alpha2_Controllers(in, out, s)
}

func autoConvert_v1alpha2_DataPlane_To_core_DataPlane(in *DataPlane, out *core.DataPlane, s conversion.Scope) error {
	if err := Convert_v1alpha2_SecretReference_To_core_SecretReference(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_v1alpha2_DataPlane_To_core_DataPlane is an autogenerated conversion function.
func Convert_v1alpha2_DataPlane_To_core_DataPlane(in *DataPlane, out *core.DataPlane, s conversion.Scope) error {
	return autoConvert_v1alpha2_DataPlane_To_core_DataPlane(in, out, s)
}

func autoConvert_core_DataPlane_To_v1alpha2_DataPlane(in *core.DataPlane, out *DataPlane, s conversion.Scope) error {
	if err := Convert_core_SecretReference_To_v1alpha2_SecretReference(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_core_DataPlane_To_v1alpha2_DataPlane is an autogenerated conversion function.
func Convert_core_DataPlane_To_v1alpha2_DataPlane(in *core.DataPlane, out *DataPlane, s conversion.Scope) error {
	return autoConvert_core_DataPlane_To_v1alpha2_DataPlane(in, out, s)
}

func autoConvert_v1alpha2_DeployItemTimeouts_To_core_DeployItemTimeouts(in *DeployItemTimeouts, out *core.DeployItemTimeouts, s conversion.Scope) error {
	out.Pickup = in.Pickup
	out.ProgressingDefault = in.ProgressingDefault
	return nil
}

// Convert_v1alpha2_DeployItemTimeouts_To_core_DeployItemTimeouts is an autogenerated conversion function.
func Convert_v1alpha2_DeployItemTimeouts_To_core_DeployItemTimeouts(in *DeployItemTimeouts, out *core.DeployItemTimeouts, s conversion.Scope) error {
	return autoConvert_v1alpha2_DeployItemTimeouts_To_core_DeployItemTimeouts(in, out, s)
}

func autoConvert_core_DeployItemTimeouts_To_v1alpha2_DeployItemTimeouts(in *core.DeployItemTimeouts, out *DeployItemTimeouts, s conversion.Scope) error {
	out.Pickup = in.Pickup
	out.ProgressingDefault = in.ProgressingDefault
	return nil
}

// Convert_core_DeployItemTimeouts_To_v1alpha2_DeployItemTimeouts is an autogenerated conversion function.
func Convert_core_DeployItemTimeouts_To_v1alpha2_DeployItemTimeouts(in *core.DeployItemTimeouts, out *DeployItemTimeouts, s conversion.Scope) error {
	return autoConvert_core_DeployItemTimeouts_To_v1alpha2_DeployItemTimeouts(in, out, s)
}

func autoConvert_v1alpha2_Deployer_To_core_Deployer(in *Deployer, out *core.Deployer, s conversion.Scope) error {
	out.Controller = (*core.Controller)(unsafe.Pointer(in.Controller))
	out.K8SClientSettings = (*core.K8SClientSettings)(unsafe.Pointer(in.K8SClientSettings))
	return nil
}

// Convert_v1alpha2_Deployer_To_core_Deployer is an autogenerated conversion function.
func Convert_v1alpha2_Deployer_To_core_Deployer(in *Deployer, out *core.Deployer, s conversion.Scope) error {
	return autoConvert_v1alpha2_Deployer_To_core_Deployer(in, out, s)
}

func autoConvert_core_Deployer_To_v1alpha2_Deployer(in *core.Deployer, out *Deployer, s conversion.Scope) error {
	out.Controller = (*Controller)(unsafe.Pointer(in.Controller))
	out.K8SClientSettings = (*K8SClientSettings)(unsafe.Pointer(in.K8SClientSettings))
	return nil
}

// Convert_core_Deployer_To_v1alpha2_Deployer is an autogenerated conversion function.
func Convert_core_Deployer_To_v1alpha2_Deployer(in *core.Deployer, out *Deployer, s conversion.Scope) error {
	return autoConvert_core_Deployer_To_v1alpha2_Deployer(in, out, s)
}

func autoConvert_v1alpha2_DeployerConfig_To_core_DeployerConfig(in *DeployerConfig, out *core.DeployerConfig, s conversion.Scope) error {
	out.Deployer = (*core.Deployer)(unsafe.Pointer(in.Deployer))
	out.Resources = (*core.Resources)(unsafe.Pointer(in.Resources))
	out.HPA = (*core.HPA)(unsafe.Pointer(in.HPA))
	return nil
}

// Convert_v1alpha2_DeployerConfig_To_core_DeployerConfig is an autogenerated conversion function.
func Convert_v1alpha2_DeployerConfig_To_core_DeployerConfig(in *DeployerConfig, out *core.DeployerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_DeployerConfig_To_core_DeployerConfig(in, out, s)
}

func autoConvert_core_DeployerConfig_To_v1alpha2_DeployerConfig(in *core.DeployerConfig, out *DeployerConfig, s conversion.Scope) error {
	out.Deployer = (*Deployer)(unsafe.Pointer(in.Deployer))
	out.Resources = (*Resources)(unsafe.Pointer(in.Resources))
	out.HPA = (*HPA)(unsafe.Pointer(in.HPA))
	return nil
}

// Convert_core_DeployerConfig_To_v1alpha2_DeployerConfig is an autogenerated conversion function.
func Convert_core_DeployerConfig_To_v1alpha2_DeployerConfig(in *core.DeployerConfig, out *DeployerConfig, s conversion.Scope) error {
	return autoConvert_core_DeployerConfig_To_v1alpha2_DeployerConfig(in, out, s)
}

func autoConvert_v1alpha2_Error_To_core_Error(in *Error, out *core.Error, s conversion.Scope) error {
	out.Operation = in.Operation
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha2_Error_To_core_Error is an autogenerated conversion function.
func Convert_v1alpha2_Error_To_core_Error(in *Error, out *core.Error, s conversion.Scope) error {
	return autoConvert_v1alpha2_Error_To_core_Error(in, out, s)
}

func autoConvert_core_Error_To_v1alpha2_Error(in *core.Error, out *Error, s conversion.Scope) error {
	out.Operation = in.Operation
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_core_Error_To_v1alpha2_Error is an autogenerated conversion function.
func Convert_core_Error_To_v1alpha2_Error(in *core.Error, out *Error, s conversion.Scope) error {
	return autoConvert_core_Error_To_v1alpha2_Error(in, out, s)
}

func autoConvert_v1alpha2_HPA_To_core_HPA(in *HPA, out *core.HPA, s conversion.Scope) error {
	out.MaxReplicas = in.MaxReplicas
	out.AverageMemoryUtilization = in.AverageMemoryUtilization
	out.AverageCpuUtilization = in.AverageCpuUtilization
	return nil
}

// Convert_v1alpha2_HPA_To_core_HPA is an autogenerated conversion function.
func Convert_v1alpha2_HPA_To_core_HPA(in *HPA, out *core.HPA, s conversion.Scope) error {
	return autoConvert_v1alpha2_HPA_To_core_HPA(in, out, s)
}

func autoConvert_core_HPA_To_v1alpha2_HPA(in *core.HPA, out *HPA, s conversion.Scope) error {
	out.MaxReplicas = in.MaxReplicas
	out.AverageMemoryUtilization = in.AverageMemoryUtilization
	out.AverageCpuUtilization = in.AverageCpuUtilization
	return nil
}

// Convert_core_HPA_To_v1alpha2_HPA is an autogenerated conversion function.
func Convert_core_HPA_To_v1alpha2_HPA(in *core.HPA, out *HPA, s conversion.Scope) error {
	return autoConvert_core_HPA_To_v1alpha2_HPA(in, out, s)
}

func autoConvert_v1alpha2_Instance_To_core_Instance(in *Instance, out *core.Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_InstanceSpec_To_core_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_InstanceStatus_To_core_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Instance_To_core_Instance is an autogenerated conversion function.
func Convert_v1alpha2_Instance_To_core_Instance(in *Instance, out *core.Instance, s conversion.Scope) error {
	return autoConvert_v1alpha2_Instance_To_core_Instance(in, out, s)
}

func autoConvert_core_Instance_To_v1alpha2_Instance(in *core.Instance, out *Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_InstanceSpec_To_v1alpha2_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_InstanceStatus_To_v1alpha2_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Instance_To_v1alpha2_Instance is an autogenerated conversion function.
func Convert_core_Instance_To_v1alpha2_Instance(in *core.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_core_Instance_To_v1alpha2_Instance(in, out, s)
}

func autoConvert_v1alpha2_InstanceList_To_core_InstanceList(in *InstanceList, out *core.InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_InstanceList_To_core_InstanceList is an autogenerated conversion function.
func Convert_v1alpha2_InstanceList_To_core_InstanceList(in *InstanceList, out *core.InstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceList_To_core_InstanceList(in, out, s)
}

func autoConvert_core_InstanceList_To_v1alpha2_InstanceList(in *core.InstanceList, out *InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_InstanceList_To_v1alpha2_InstanceList is an autogenerated conversion function.
func Convert_core_InstanceList_To_v1alpha2_InstanceList(in *core.InstanceList, out *InstanceList, s conversion.Scope) error {
	return autoConvert_core_InstanceList_To_v1alpha2_InstanceList(in, out, s)
}

func autoConvert_v1alpha2_InstanceSpec_To_core_InstanceSpec(in *InstanceSpec, out *core.InstanceSpec, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.ID = in.ID
	if err := Convert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(&in.LandscaperConfiguration, &out.LandscaperConfiguration, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ObjectReference_To_core_ObjectReference(&in.ServiceTargetConfigRef, &out.ServiceTargetConfigRef, s); err != nil {
		return err
	}
	out.AutomaticReconcile = (*core.AutomaticReconcile)(unsafe.Pointer(in.AutomaticReconcile))
	if err := Convert_v1alpha2_DataPlane_To_core_DataPlane(&in.DataPlane, &out.DataPlane, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InstanceSpec_To_core_InstanceSpec is an autogenerated conversion function.
func Convert_v1alpha2_InstanceSpec_To_core_InstanceSpec(in *InstanceSpec, out *core.InstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceSpec_To_core_InstanceSpec(in, out, s)
}

func autoConvert_core_InstanceSpec_To_v1alpha2_InstanceSpec(in *core.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.ID = in.ID
	if err := Convert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(&in.LandscaperConfiguration, &out.LandscaperConfiguration, s); err != nil {
		return err
	}
	if err := Convert_core_ObjectReference_To_v1alpha2_ObjectReference(&in.ServiceTargetConfigRef, &out.ServiceTargetConfigRef, s); err != nil {
		return err
	}
	out.AutomaticReconcile = (*AutomaticReconcile)(unsafe.Pointer(in.AutomaticReconcile))
	if err := Convert_core_DataPlane_To_v1alpha2_DataPlane(&in.DataPlane, &out.DataPlane, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_InstanceSpec_To_v1alpha2_InstanceSpec is an autogenerated conversion function.
func Convert_core_InstanceSpec_To_v1alpha2_InstanceSpec(in *core.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	return autoConvert_core_InstanceSpec_To_v1alpha2_InstanceSpec(in, out, s)
}

func autoConvert_v1alpha2_InstanceStatus_To_core_InstanceStatus(in *InstanceStatus, out *core.InstanceStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastError = (*core.Error)(unsafe.Pointer(in.LastError))
	out.LandscaperServiceComponent = (*core.LandscaperServiceComponent)(unsafe.Pointer(in.LandscaperServiceComponent))
	out.ContextRef = (*core.ObjectReference)(unsafe.Pointer(in.ContextRef))
	out.TargetRef = (*core.ObjectReference)(unsafe.Pointer(in.TargetRef))
	out.GardenerServiceAccountRef = (*core.ObjectReference)(unsafe.Pointer(in.GardenerServiceAccountRef))
	out.InstallationRef = (*core.ObjectReference)(unsafe.Pointer(in.InstallationRef))
	out.ClusterEndpoint = in.ClusterEndpoint
	out.UserKubeconfig = in.UserKubeconfig
	out.AdminKubeconfig = in.AdminKubeconfig
	out.ShootName = in.ShootName
	out.ShootNamespace = in.ShootNamespace
	return nil
}

// Convert_v1alpha2_InstanceStatus_To_core_InstanceStatus is an autogenerated conversion function.
func Convert_v1alpha2_InstanceStatus_To_core_InstanceStatus(in *InstanceStatus, out *core.InstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceStatus_To_core_InstanceStatus(in, out, s)
}

func autoConvert_core_InstanceStatus_To_v1alpha2_InstanceStatus(in *core.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastError = (*Error)(unsafe.Pointer(in.LastError))
	out.LandscaperServiceComponent = (*LandscaperServiceComponent)(unsafe.Pointer(in.LandscaperServiceComponent))
	out.ContextRef = (*ObjectReference)(unsafe.Pointer(in.ContextRef))
	out.TargetRef = (*ObjectReference)(unsafe.Pointer(in.TargetRef))
	out.GardenerServiceAccountRef = (*ObjectReference)(unsafe.Pointer(in.GardenerServiceAccountRef))
	out.InstallationRef = (*ObjectReference)(unsafe.Pointer(in.InstallationRef))
	out.ClusterEndpoint = in.ClusterEndpoint
	out.UserKubeconfig = in.UserKubeconfig
	out.AdminKubeconfig = in.AdminKubeconfig
	out.ShootName = in.ShootName
	out.ShootNamespace = in.ShootNamespace
	return nil
}

// Convert_core_InstanceStatus_To_v1alpha2_InstanceStatus is an autogenerated conversion function.
func Convert_core_InstanceStatus_To_v1alpha2_InstanceStatus(in *core.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	return autoConvert_core_InstanceStatus_To_v1alpha2_InstanceStatus(in, out, s)
}

func autoConvert_v1alpha2_K8SClientLimits_To_core_K8SClientLimits(in *K8SClientLimits, out *core.K8SClientLimits, s conversion.Scope) error {
	out.Burst = in.Burst
	out.QPS = in.QPS
	return nil
}

// Convert_v1alpha2_K8SClientLimits_To_core_K8SClientLimits is an autogenerated conversion function.
func Convert_v1alpha2_K8SClientLimits_To_core_K8SClientLimits(in *K8SClientLimits, out *core.K8SClientLimits, s conversion.Scope) error {
	return autoConvert_v1alpha2_K8SClientLimits_To_core_K8SClientLimits(in, out, s)
}

func autoConvert_core_K8SClientLimits_To_v1alpha2_K8SClientLimits(in *core.K8SClientLimits, out *K8SClientLimits, s conversion.Scope) error {
	out.Burst = in.Burst
	out.QPS = in.QPS
	return nil
}

// Convert_core_K8SClientLimits_To_v1alpha2_K8SClientLimits is an autogenerated conversion function.
func Convert_core_K8SClientLimits_To_v1alpha2_K8SClientLimits(in *core.K8SClientLimits, out *K8SClientLimits, s conversion.Scope) error {
	return autoConvert_core_K8SClientLimits_To_v1alpha2_K8SClientLimits(in, out, s)
}

func autoConvert_v1alpha2_K8SClientSettings_To_core_K8SClientSettings(in *K8SClientSettings, out *core.K8SClientSettings, s conversion.Scope) error {
	out.HostClient = (*core.K8SClientLimits)(unsafe.Pointer(in.HostClient))
	out.ResourceClient = (*core.K8SClientLimits)(unsafe.Pointer(in.ResourceClient))
	return nil
}

// Convert_v1alpha2_K8SClientSettings_To_core_K8SClientSettings is an autogenerated conversion function.
func Convert_v1alpha2_K8SClientSettings_To_core_K8SClientSettings(in *K8SClientSettings, out *core.K8SClientSettings, s conversion.Scope) error {
	return autoConvert_v1alpha2_K8SClientSettings_To_core_K8SClientSettings(in, out, s)
}

func autoConvert_core_K8SClientSettings_To_v1alpha2_K8SClientSettings(in *core.K8SClientSettings, out *K8SClientSettings, s conversion.Scope) error {
	out.HostClient = (*K8SClientLimits)(unsafe.Pointer(in.HostClient))
	out.ResourceClient = (*K8SClientLimits)(unsafe.Pointer(in.ResourceClient))
	return nil
}

// Convert_core_K8SClientSettings_To_v1alpha2_K8SClientSettings is an autogenerated conversion function.
func Convert_core_K8SClientSettings_To_v1alpha2_K8SClientSettings(in *core.K8SClientSettings, out *K8SClientSettings, s conversion.Scope) error {
	return autoConvert_core_K8SClientSettings_To_v1alpha2_K8SClientSettings(in, out, s)
}

func autoConvert_v1alpha2_Landscaper_To_core_Landscaper(in *Landscaper, out *core.Landscaper, s conversion.Scope) error {
	out.Controllers = (*core.Controllers)(unsafe.Pointer(in.Controllers))
	out.K8SClientSettings = (*core.K8SClientSettings)(unsafe.Pointer(in.K8SClientSettings))
	out.DeployItemTimeouts = (*core.DeployItemTimeouts)(unsafe.Pointer(in.DeployItemTimeouts))
	return nil
}

// Convert_v1alpha2_Landscaper_To_core_Landscaper is an autogenerated conversion function.
func Convert_v1alpha2_Landscaper_To_core_Landscaper(in *Landscaper, out *core.Landscaper, s conversion.Scope) error {
	return autoConvert_v1alpha2_Landscaper_To_core_Landscaper(in, out, s)
}

func autoConvert_core_Landscaper_To_v1alpha2_Landscaper(in *core.Landscaper, out *Landscaper, s conversion.Scope) error {
	out.Controllers = (*Controllers)(unsafe.Pointer(in.Controllers))
	out.K8SClientSettings = (*K8SClientSettings)(unsafe.Pointer(in.K8SClientSettings))
	out.DeployItemTimeouts = (*DeployItemTimeouts)(unsafe.Pointer(in.DeployItemTimeouts))
	return nil
}

// Convert_core_Landscaper_To_v1alpha2_Landscaper is an autogenerated conversion function.
func Convert_core_Landscaper_To_v1alpha2_Landscaper(in *core.Landscaper, out *Landscaper, s conversion.Scope) error {
	return autoConvert_core_Landscaper_To_v1alpha2_Landscaper(in, out, s)
}

func autoConvert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(in *LandscaperConfiguration, out *core.LandscaperConfiguration, s conversion.Scope) error {
	out.Landscaper = (*core.Landscaper)(unsafe.Pointer(in.Landscaper))
	out.Resources = (*core.Resources)(unsafe.Pointer(in.Resources))
	out.ResourcesMain = (*core.Resources)(unsafe.Pointer(in.ResourcesMain))
	out.HPAMain = (*core.HPA)(unsafe.Pointer(in.HPAMain))
	out.Deployers = *(*[]string)(unsafe.Pointer(&in.Deployers))
	out.DeployersConfig = *(*map[string]*core.DeployerConfig)(unsafe.Pointer(&in.DeployersConfig))
	return nil
}

// Convert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(in *LandscaperConfiguration, out *core.LandscaperConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(in, out, s)
}

func autoConvert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(in *core.LandscaperConfiguration, out *LandscaperConfiguration, s conversion.Scope) error {
	out.Landscaper = (*Landscaper)(unsafe.Pointer(in.Landscaper))
	out.Resources = (*Resources)(unsafe.Pointer(in.Resources))
	out.ResourcesMain = (*Resources)(unsafe.Pointer(in.ResourcesMain))
	out.HPAMain = (*HPA)(unsafe.Pointer(in.HPAMain))
	out.Deployers = *(*[]string)(unsafe.Pointer(&in.Deployers))
	out.DeployersConfig = *(*map[string]*DeployerConfig)(unsafe.Pointer(&in.DeployersConfig))
	return nil
}

// Convert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration is an autogenerated conversion function.
func Convert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(in *core.LandscaperConfiguration, out *LandscaperConfiguration, s conversion.Scope) error {
	return autoConvert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(in, out, s)
}

func autoConvert_v1alpha2_LandscaperDeployment_To_core_LandscaperDeployment(in *LandscaperDeployment, out *core.LandscaperDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LandscaperDeployment_To_core_LandscaperDeployment is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperDeployment_To_core_LandscaperDeployment(in *LandscaperDeployment, out *core.LandscaperDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperDeployment_To_core_LandscaperDeployment(in, out, s)
}

func autoConvert_core_LandscaperDeployment_To_v1alpha2_LandscaperDeployment(in *core.LandscaperDeployment, out *LandscaperDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_LandscaperDeployment_To_v1alpha2_LandscaperDeployment is an autogenerated conversion function.
func Convert_core_LandscaperDeployment_To_v1alpha2_LandscaperDeployment(in *core.LandscaperDeployment, out *LandscaperDeployment, s conversion.Scope) error {
	return autoConvert_core_LandscaperDeployment_To_v1alpha2_LandscaperDeployment(in, out, s)
}

func autoConvert_v1alpha2_LandscaperDeploymentList_To_core_LandscaperDeploymentList(in *LandscaperDeploymentList, out *core.LandscaperDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.LandscaperDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_LandscaperDeploymentList_To_core_LandscaperDeploymentList is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperDeploymentList_To_core_LandscaperDeploymentList(in *LandscaperDeploymentList, out *core.LandscaperDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperDeploymentList_To_core_LandscaperDeploymentList(in, out, s)
}

func autoConvert_core_LandscaperDeploymentList_To_v1alpha2_LandscaperDeploymentList(in *core.LandscaperDeploymentList, out *LandscaperDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LandscaperDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_LandscaperDeploymentList_To_v1alpha2_LandscaperDeploymentList is an autogenerated conversion function.
func Convert_core_LandscaperDeploymentList_To_v1alpha2_LandscaperDeploymentList(in *core.LandscaperDeploymentList, out *LandscaperDeploymentList, s conversion.Scope) error {
	return autoConvert_core_LandscaperDeploymentList_To_v1alpha2_LandscaperDeploymentList(in, out, s)
}

func autoConvert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec(in *LandscaperDeploymentSpec, out *core.LandscaperDeploymentSpec, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.Purpose = in.Purpose
	if err := Convert_v1alpha2_LandscaperConfiguration_To_core_LandscaperConfiguration(&in.LandscaperConfiguration, &out.LandscaperConfiguration, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_DataPlane_To_core_DataPlane(&in.DataPlane, &out.DataPlane, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec(in *LandscaperDeploymentSpec, out *core.LandscaperDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperDeploymentSpec_To_core_LandscaperDeploymentSpec(in, out, s)
}

func autoConvert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec(in *core.LandscaperDeploymentSpec, out *LandscaperDeploymentSpec, s conversion.Scope) error {
	out.TenantId = in.TenantId
	out.Purpose = in.Purpose
	if err := Convert_core_LandscaperConfiguration_To_v1alpha2_LandscaperConfiguration(&in.LandscaperConfiguration, &out.LandscaperConfiguration, s); err != nil {
		return err
	}
	if err := Convert_core_DataPlane_To_v1alpha2_DataPlane(&in.DataPlane, &out.DataPlane, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec is an autogenerated conversion function.
func Convert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec(in *core.LandscaperDeploymentSpec, out *LandscaperDeploymentSpec, s conversion.Scope) error {
	return autoConvert_core_LandscaperDeploymentSpec_To_v1alpha2_LandscaperDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus(in *LandscaperDeploymentStatus, out *core.LandscaperDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastError = (*core.Error)(unsafe.Pointer(in.LastError))
	out.InstanceRef = (*core.ObjectReference)(unsafe.Pointer(in.InstanceRef))
	return nil
}

// Convert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus(in *LandscaperDeploymentStatus, out *core.LandscaperDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperDeploymentStatus_To_core_LandscaperDeploymentStatus(in, out, s)
}

func autoConvert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus(in *core.LandscaperDeploymentStatus, out *LandscaperDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.LastError = (*Error)(unsafe.Pointer(in.LastError))
	out.InstanceRef = (*ObjectReference)(unsafe.Pointer(in.InstanceRef))
	return nil
}

// Convert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus is an autogenerated conversion function.
func Convert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus(in *core.LandscaperDeploymentStatus, out *LandscaperDeploymentStatus, s conversion.Scope) error {
	return autoConvert_core_LandscaperDeploymentStatus_To_v1alpha2_LandscaperDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha2_LandscaperServiceComponent_To_core_LandscaperServiceComponent(in *LandscaperServiceComponent, out *core.LandscaperServiceComponent, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1alpha2_LandscaperServiceComponent_To_core_LandscaperServiceComponent is an autogenerated conversion function.
func Convert_v1alpha2_LandscaperServiceComponent_To_core_LandscaperServiceComponent(in *LandscaperServiceComponent, out *core.LandscaperServiceComponent, s conversion.Scope) error {
	return autoConvert_v1alpha2_LandscaperServiceComponent_To_core_LandscaperServiceComponent(in, out, s)
}

func autoConvert_core_LandscaperServiceComponent_To_v1alpha2_LandscaperServiceComponent(in *core.LandscaperServiceComponent, out *LandscaperServiceComponent, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_core_LandscaperServiceComponent_To_v1alpha2_LandscaperServiceComponent is an autogenerated conversion function.
func Convert_core_LandscaperServiceComponent_To_v1alpha2_LandscaperServiceComponent(in *core.LandscaperServiceComponent, out *LandscaperServiceComponent, s conversion.Scope) error {
	return autoConvert_core_LandscaperServiceComponent_To_v1alpha2_LandscaperServiceComponent(in, out, s)
}

func autoConvert_v1alpha2_NamespaceRegistration_To_core_NamespaceRegistration(in *NamespaceRegistration, out *core.NamespaceRegistration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_NamespaceRegistration_To_core_NamespaceRegistration is an autogenerated conversion function.
func Convert_v1alpha2_NamespaceRegistration_To_core_NamespaceRegistration(in *NamespaceRegistration, out *core.NamespaceRegistration, s conversion.Scope) error {
	return autoConvert_v1alpha2_NamespaceRegistration_To_core_NamespaceRegistration(in, out, s)
}

func autoConvert_core_NamespaceRegistration_To_v1alpha2_NamespaceRegistration(in *core.NamespaceRegistration, out *NamespaceRegistration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_NamespaceRegistration_To_v1alpha2_NamespaceRegistration is an autogenerated conversion function.
func Convert_core_NamespaceRegistration_To_v1alpha2_NamespaceRegistration(in *core.NamespaceRegistration, out *NamespaceRegistration, s conversion.Scope) error {
	return autoConvert_core_NamespaceRegistration_To_v1alpha2_NamespaceRegistration(in, out, s)
}

func autoConvert_v1alpha2_NamespaceRegistrationList_To_core_NamespaceRegistrationList(in *NamespaceRegistrationList, out *core.NamespaceRegistrationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.NamespaceRegistration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_NamespaceRegistrationList_To_core_NamespaceRegistrationList is an autogenerated conversion function.
func Convert_v1alpha2_NamespaceRegistrationList_To_core_NamespaceRegistrationList(in *NamespaceRegistrationList, out *core.NamespaceRegistrationList, s conversion.Scope) error {
	return autoConvert_v1alpha2_NamespaceRegistrationList_To_core_NamespaceRegistrationList(in, out, s)
}

func autoConvert_core_NamespaceRegistrationList_To_v1alpha2_NamespaceRegistrationList(in *core.NamespaceRegistrationList, out *NamespaceRegistrationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NamespaceRegistration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_NamespaceRegistrationList_To_v1alpha2_NamespaceRegistrationList is an autogenerated conversion function.
func Convert_core_NamespaceRegistrationList_To_v1alpha2_NamespaceRegistrationList(in *core.NamespaceRegistrationList, out *NamespaceRegistrationList, s conversion.Scope) error {
	return autoConvert_core_NamespaceRegistrationList_To_v1alpha2_NamespaceRegistrationList(in, out, s)
}

func autoConvert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec(in *NamespaceRegistrationSpec, out *core.NamespaceRegistrationSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec is an autogenerated conversion function.
func Convert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec(in *NamespaceRegistrationSpec, out *core.NamespaceRegistrationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NamespaceRegistrationSpec_To_core_NamespaceRegistrationSpec(in, out, s)
}

func autoConvert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec(in *core.NamespaceRegistrationSpec, out *NamespaceRegistrationSpec, s conversion.Scope) error {
	return nil
}

// Convert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec is an autogenerated conversion function.
func Convert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec(in *core.NamespaceRegistrationSpec, out *NamespaceRegistrationSpec, s conversion.Scope) error {
	return autoConvert_core_NamespaceRegistrationSpec_To_v1alpha2_NamespaceRegistrationSpec(in, out, s)
}

func autoConvert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus(in *NamespaceRegistrationStatus, out *core.NamespaceRegistrationStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.LastError = (*core.Error)(unsafe.Pointer(in.LastError))
	return nil
}

// Convert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus is an autogenerated conversion function.
func Convert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus(in *NamespaceRegistrationStatus, out *core.NamespaceRegistrationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NamespaceRegistrationStatus_To_core_NamespaceRegistrationStatus(in, out, s)
}

func autoConvert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus(in *core.NamespaceRegistrationStatus, out *NamespaceRegistrationStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.LastError = (*Error)(unsafe.Pointer(in.LastError))
	return nil
}

// Convert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus is an autogenerated conversion function.
func Convert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus(in *core.NamespaceRegistrationStatus, out *NamespaceRegistrationStatus, s conversion.Scope) error {
	return autoConvert_core_NamespaceRegistrationStatus_To_v1alpha2_NamespaceRegistrationStatus(in, out, s)
}

func autoConvert_v1alpha2_ObjectReference_To_core_ObjectReference(in *ObjectReference, out *core.ObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha2_ObjectReference_To_core_ObjectReference is an autogenerated conversion function.
func Convert_v1alpha2_ObjectReference_To_core_ObjectReference(in *ObjectReference, out *core.ObjectReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_ObjectReference_To_core_ObjectReference(in, out, s)
}

func autoConvert_core_ObjectReference_To_v1alpha2_ObjectReference(in *core.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_core_ObjectReference_To_v1alpha2_ObjectReference is an autogenerated conversion function.
func Convert_core_ObjectReference_To_v1alpha2_ObjectReference(in *core.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	return autoConvert_core_ObjectReference_To_v1alpha2_ObjectReference(in, out, s)
}

func autoConvert_v1alpha2_ResourceRequests_To_core_ResourceRequests(in *ResourceRequests, out *core.ResourceRequests, s conversion.Scope) error {
	out.CPU = in.CPU
	out.Memory = in.Memory
	return nil
}

// Convert_v1alpha2_ResourceRequests_To_core_ResourceRequests is an autogenerated conversion function.
func Convert_v1alpha2_ResourceRequests_To_core_ResourceRequests(in *ResourceRequests, out *core.ResourceRequests, s conversion.Scope) error {
	return autoConvert_v1alpha2_ResourceRequests_To_core_ResourceRequests(in, out, s)
}

func autoConvert_core_ResourceRequests_To_v1alpha2_ResourceRequests(in *core.ResourceRequests, out *ResourceRequests, s conversion.Scope) error {
	out.CPU = in.CPU
	out.Memory = in.Memory
	return nil
}

// Convert_core_ResourceRequests_To_v1alpha2_ResourceRequests is an autogenerated conversion function.
func Convert_core_ResourceRequests_To_v1alpha2_ResourceRequests(in *core.ResourceRequests, out *ResourceRequests, s conversion.Scope) error {
	return autoConvert_core_ResourceRequests_To_v1alpha2_ResourceRequests(in, out, s)
}

func autoConvert_v1alpha2_Resources_To_core_Resources(in *Resources, out *core.Resources, s conversion.Scope) error {
	if err := Convert_v1alpha2_ResourceRequests_To_core_ResourceRequests(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Resources_To_core_Resources is an autogenerated conversion function.
func Convert_v1alpha2_Resources_To_core_Resources(in *Resources, out *core.Resources, s conversion.Scope) error {
	return autoConvert_v1alpha2_Resources_To_core_Resources(in, out, s)
}

func autoConvert_core_Resources_To_v1alpha2_Resources(in *core.Resources, out *Resources, s conversion.Scope) error {
	if err := Convert_core_ResourceRequests_To_v1alpha2_ResourceRequests(&in.Requests, &out.Requests, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Resources_To_v1alpha2_Resources is an autogenerated conversion function.
func Convert_core_Resources_To_v1alpha2_Resources(in *core.Resources, out *Resources, s conversion.Scope) error {
	return autoConvert_core_Resources_To_v1alpha2_Resources(in, out, s)
}

func autoConvert_v1alpha2_SecretReference_To_core_SecretReference(in *SecretReference, out *core.SecretReference, s conversion.Scope) error {
	if err := Convert_v1alpha2_ObjectReference_To_core_ObjectReference(&in.ObjectReference, &out.ObjectReference, s); err != nil {
		return err
	}
	out.Key = in.Key
	return nil
}

// Convert_v1alpha2_SecretReference_To_core_SecretReference is an autogenerated conversion function.
func Convert_v1alpha2_SecretReference_To_core_SecretReference(in *SecretReference, out *core.SecretReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_SecretReference_To_core_SecretReference(in, out, s)
}

func autoConvert_core_SecretReference_To_v1alpha2_SecretReference(in *core.SecretReference, out *SecretReference, s conversion.Scope) error {
	if err := Convert_core_ObjectReference_To_v1alpha2_ObjectReference(&in.ObjectReference, &out.ObjectReference, s); err != nil {
		return err
	}
	out.Key = in.Key
	return nil
}

// Convert_core_SecretReference_To_v1alpha2_SecretReference is an autogenerated conversion function.
func Convert_core_SecretReference_To_v1alpha2_SecretReference(in *core.SecretReference, out *SecretReference, s conversion.Scope) error {
	return autoConvert_core_SecretReference_To_v1alpha2_SecretReference(in, out, s)
}

func autoConvert_v1alpha2_ServiceTargetConfig_To_core_ServiceTargetConfig(in *ServiceTargetConfig, out *core.ServiceTargetConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ServiceTargetConfig_To_core_ServiceTargetConfig is an autogenerated conversion function.
func Convert_v1alpha2_ServiceTargetConfig_To_core_ServiceTargetConfig(in *ServiceTargetConfig, out *core.ServiceTargetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_ServiceTargetConfig_To_core_ServiceTargetConfig(in, out, s)
}

func autoConvert_core_ServiceTargetConfig_To_v1alpha2_ServiceTargetConfig(in *core.ServiceTargetConfig, out *ServiceTargetConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_ServiceTargetConfig_To_v1alpha2_ServiceTargetConfig is an autogenerated conversion function.
func Convert_core_ServiceTargetConfig_To_v1alpha2_ServiceTargetConfig(in *core.ServiceTargetConfig, out *ServiceTargetConfig, s conversion.Scope) error {
	return autoConvert_core_ServiceTargetConfig_To_v1alpha2_ServiceTargetConfig(in, out, s)
}

func autoConvert_v1alpha2_ServiceTargetConfigList_To_core_ServiceTargetConfigList(in *ServiceTargetConfigList, out *core.ServiceTargetConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.ServiceTargetConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_ServiceTargetConfigList_To_core_ServiceTargetConfigList is an autogenerated conversion function.
func Convert_v1alpha2_ServiceTargetConfigList_To_core_ServiceTargetConfigList(in *ServiceTargetConfigList, out *core.ServiceTargetConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ServiceTargetConfigList_To_core_ServiceTargetConfigList(in, out, s)
}

func autoConvert_core_ServiceTargetConfigList_To_v1alpha2_ServiceTargetConfigList(in *core.ServiceTargetConfigList, out *ServiceTargetConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ServiceTargetConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_ServiceTargetConfigList_To_v1alpha2_ServiceTargetConfigList is an autogenerated conversion function.
func Convert_core_ServiceTargetConfigList_To_v1alpha2_ServiceTargetConfigList(in *core.ServiceTargetConfigList, out *ServiceTargetConfigList, s conversion.Scope) error {
	return autoConvert_core_ServiceTargetConfigList_To_v1alpha2_ServiceTargetConfigList(in, out, s)
}

func autoConvert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec(in *ServiceTargetConfigSpec, out *core.ServiceTargetConfigSpec, s conversion.Scope) error {
	out.Priority = in.Priority
	if err := Convert_v1alpha2_SecretReference_To_core_SecretReference(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	out.IngressDomain = in.IngressDomain
	return nil
}

// Convert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec is an autogenerated conversion function.
func Convert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec(in *ServiceTargetConfigSpec, out *core.ServiceTargetConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ServiceTargetConfigSpec_To_core_ServiceTargetConfigSpec(in, out, s)
}

func autoConvert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec(in *core.ServiceTargetConfigSpec, out *ServiceTargetConfigSpec, s conversion.Scope) error {
	out.Priority = in.Priority
	if err := Convert_core_SecretReference_To_v1alpha2_SecretReference(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	out.IngressDomain = in.IngressDomain
	return nil
}

// Convert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec is an autogenerated conversion function.
func Convert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec(in *core.ServiceTargetConfigSpec, out *ServiceTargetConfigSpec, s conversion.Scope) error {
	return autoConvert_core_ServiceTargetConfigSpec_To_v1alpha2_ServiceTargetConfigSpec(in, out, s)
}

func autoConvert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus(in *ServiceTargetConfigStatus, out *core.ServiceTargetConfigStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.InstanceRefs = *(*[]core.ObjectReference)(unsafe.Pointer(&in.InstanceRefs))
	return nil
}

// Convert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus is an autogenerated conversion function.
func Convert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus(in *ServiceTargetConfigStatus, out *core.ServiceTargetConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ServiceTargetConfigStatus_To_core_ServiceTargetConfigStatus(in, out, s)
}

func autoConvert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus(in *core.ServiceTargetConfigStatus, out *ServiceTargetConfigStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.InstanceRefs = *(*[]ObjectReference)(unsafe.Pointer(&in.InstanceRefs))
	return nil
}

// Convert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus is an autogenerated conversion function.
func Convert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus(in *core.ServiceTargetConfigStatus, out *ServiceTargetConfigStatus, s conversion.Scope) error {
	return autoConvert_core_ServiceTargetConfigStatus_To_v1alpha2_ServiceTargetConfigStatus(in, out, s)
}

func autoConvert_v1alpha2_Subject_To_core_Subject(in *Subject, out *core.Subject, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha2_Subject_To_core_Subject is an autogenerated conversion function.
func Convert_v1alpha2_Subject_To_core_Subject(in *Subject, out *core.Subject, s conversion.Scope) error {
	return autoConvert_v1alpha2_Subject_To_core_Subject(in, out, s)
}

func autoConvert_core_Subject_To_v1alpha2_Subject(in *core.Subject, out *Subject, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_core_Subject_To_v1alpha2_Subject is an autogenerated conversion function.
func Convert_core_Subject_To_v1alpha2_Subject(in *core.Subject, out *Subject, s conversion.Scope) error {
	return autoConvert_core_Subject_To_v1alpha2_Subject(in, out, s)
}

func autoConvert_v1alpha2_SubjectList_To_core_SubjectList(in *SubjectList, out *core.SubjectList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_SubjectList_To_core_SubjectList is an autogenerated conversion function.
func Convert_v1alpha2_SubjectList_To_core_SubjectList(in *SubjectList, out *core.SubjectList, s conversion.Scope) error {
	return autoConvert_v1alpha2_SubjectList_To_core_SubjectList(in, out, s)
}

func autoConvert_core_SubjectList_To_v1alpha2_SubjectList(in *core.SubjectList, out *SubjectList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_SubjectList_To_v1alpha2_SubjectList is an autogenerated conversion function.
func Convert_core_SubjectList_To_v1alpha2_SubjectList(in *core.SubjectList, out *SubjectList, s conversion.Scope) error {
	return autoConvert_core_SubjectList_To_v1alpha2_SubjectList(in, out, s)
}

func autoConvert_v1alpha2_SubjectListList_To_core_SubjectListList(in *SubjectListList, out *core.SubjectListList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.SubjectList)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_SubjectListList_To_core_SubjectListList is an autogenerated conversion function.
func Convert_v1alpha2_SubjectListList_To_core_SubjectListList(in *SubjectListList, out *core.SubjectListList, s conversion.Scope) error {
	return autoConvert_v1alpha2_SubjectListList_To_core_SubjectListList(in, out, s)
}

func autoConvert_core_SubjectListList_To_v1alpha2_SubjectListList(in *core.SubjectListList, out *SubjectListList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SubjectList)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_SubjectListList_To_v1alpha2_SubjectListList is an autogenerated conversion function.
func Convert_core_SubjectListList_To_v1alpha2_SubjectListList(in *core.SubjectListList, out *SubjectListList, s conversion.Scope) error {
	return autoConvert_core_SubjectListList_To_v1alpha2_SubjectListList(in, out, s)
}

func autoConvert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec(in *SubjectListSpec, out *core.SubjectListSpec, s conversion.Scope) error {
	out.Subjects = *(*[]core.Subject)(unsafe.Pointer(&in.Subjects))
	return nil
}

// Convert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec is an autogenerated conversion function.
func Convert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec(in *SubjectListSpec, out *core.SubjectListSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_SubjectListSpec_To_core_SubjectListSpec(in, out, s)
}

func autoConvert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec(in *core.SubjectListSpec, out *SubjectListSpec, s conversion.Scope) error {
	out.Subjects = *(*[]Subject)(unsafe.Pointer(&in.Subjects))
	return nil
}

// Convert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec is an autogenerated conversion function.
func Convert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec(in *core.SubjectListSpec, out *SubjectListSpec, s conversion.Scope) error {
	return autoConvert_core_SubjectListSpec_To_v1alpha2_SubjectListSpec(in, out, s)
}

func autoConvert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus(in *SubjectListStatus, out *core.SubjectListStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus is an autogenerated conversion function.
func Convert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus(in *SubjectListStatus, out *core.SubjectListStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_SubjectListStatus_To_core_SubjectListStatus(in, out, s)
}

func autoConvert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus(in *core.SubjectListStatus, out *SubjectListStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus is an autogenerated conversion function.
func Convert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus(in *core.SubjectListStatus, out *SubjectListStatus, s conversion.Scope) error {
	return autoConvert_core_SubjectListStatus_To_v1alpha2_SubjectListStatus(in, out, s)
}
