apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: shootCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: targetClusterNamespace
    required: true
    type: data
    schema:
      type: string

  - name: rotationConfig
    type: data
    schema:
      description: |
        The configuration for the rotation of credentials.
      $ref: "cd://resources/rotation-config-definition"

exports:
  - name: sidecarControllerKubeconfigYaml
    type: data
    schema:
      type: string

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
