apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

exports:
  - name: certManagerReady
    type: data
    schema:
      type: boolean

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate
